RegisterNetEvent('ZC-Customscripts:ox', function()
	local playerPed = PlayerPedId()
	local coords = GetEntityCoords(playerPed)
	local boneIndex = GetPedBoneIndex(playerPed, 12844)
	local boneIndex2 = GetPedBoneIndex(playerPed, 24818)
    local object = CreateObject(GetHashKey('p_s_scuba_mask_s'), coords.x, coords.y, coords.z - 3, true, true, true)
    local object2 = CreateObject(GetHashKey('p_s_scuba_tank_s'), coords.x, coords.y, coords.z - 3, true, true, true)
    AttachEntityToEntity(object2, playerPed, boneIndex2, -0.30, -0.22, 0.0, 0.0, 90.0, 180.0, true, true, false, true, 1, true)
    AttachEntityToEntity(object, playerPed, boneIndex, 0.0, 0.0, 0.0, 0.0, 90.0, 180.0, true, true, false, true, 1, true)
    SetPedDiesInWater(playerPed, false)
    W.Notify("OXIGENO", 'Bombona colocada correctamente. Oxígeno: 100%')
end)