Housing = {}
Housing.Weights = {
    [1] = 250,
    [2] = 500,
    [3] = 1000
}

Housing['addBlips'] = false

Housing['points'] = {
    {name = "<span style='color: yellow'>Main Shells</span>", type='separator'},
    {shell = "shell_v16low", name = 'Low Shell', x = 4.63, y = -6.56, z = -1.15},
    {shell = "shell_v16mid", name = 'Mid Shell', x = 1.39, y = -14.13, z = -1.04},
    {shell = "shell_highend", name = 'High End Shell', x = -22.23, y = -0.42, z = 5.07},
    {shell = "shell_ranch", name = 'Ranch Shell <span style="color: yellow">(BIG)</span>', x = -0.72, y = -5.46, z = 0.21},

    {name = "<span style='color: yellow'>GTA Shells</span>", type='separator'},
    {shell = "shell_michael", name = 'Michael Shell', x = -9.42, y = 5.58, z = 7.73},
    {shell = "shell_frankaunt", name = 'Franklin Shell', x = -0.30, y = -5.20, z = 0.24},
    {shell = "shell_lester", name = 'Lester Shell', x = -1.69, y = -5.88, z = -1.14},
    {shell = "shell_trevor", name = 'Trevor Shell', x = 0.24, y = -3.76, z = 0.24},
    {shell = "shell_trailer", name ='Trevor Trailer', x = -1.33, y = -2.05, z = 0.71},

    {name = "<span style='color: yellow'>Breze Shells</span>", type='separator'},
    {shell = "breze_shell_01",name = 'Breeze <span style="color: yellow">Nº1</span>',  x = 1.0, y = -2.0, z = -0.98},
    {shell = "breze_shell_02", name = 'Breeze <span style="color: yellow">Nº2</span>', x = -1.50, y = 7.60, z = -0.98},
    --{shell = "breze_shell_03", name = 'Breeze <span style="color: yellow">Nº3</span>', x = -0.65, y = -7.35, z = -0.98},

    {name = "<span style='color: yellow'>Gang Shells</span>", type='separator'},
    {shell = "shell_warehouse3", name = 'Warehouse <span style="color: yellow">LEVEL 1</span>', x = 2.0, y = -1.75, z = -0.98},
    {shell = "shell_warehouse1", name = 'Warehouse <span style="color: yellow">LEVEL 2</span>', x = -8.5, y = 0.15, z = -0.98},
    {shell = "shell_warehouse2", name = 'Warehouse <span style="color: yellow">LEVEL 3</span>', x = -12.22, y = 5.58, z = -1.25},
}

Housing['shellDict'] = {
    {shell = "shell_trevor", txd = 'v_61_txd', txn = 'mh_v_trev_wallwoodpanel_d', type = "pared"},
    
    {shell = "shell_v16mid", txd = 'v_16_midapttex', txn = 'tl_v_apartmentmid_floor_wood', type = "suelo"},
    {shell = "shell_v16mid", txd = 'v_16_midapttex', txn = 'tl_v_psycheoffice_wall1', type = "pared"},
    
    {shell = "shell_v16low", txd = 'v_16_studio_lo', txn = 'gz_v_fa_carpet01', type = "suelo"},

    {shell = "shell_highend", txd = 'v_16_high_txd', txn = 'mh_v_solidwhite_d', type = "pared"},
    
    {shell = "shell_michael", txd = 'v_44_txd', txn = 'tl_v_michael_floor_terracotta', type = "suelo"},
    {shell = "shell_michael", txd = 'v_44_txd', txn = 'nxg_tl_v_michael_wall1', type = "pared"},
    
    {shell = "shell_office1", txd = 'shell_office1_txd', txn = 'km_v_p_parquet', type = "suelo"},
    {shell = "shell_office1", txd = 'shell_office1_txd', txn = 'nxg_tl_v_psycheoffice_wall1', type = "pared"},
    
    {shell = "shell_frankaunt", txd = 'frankaunttextures', txn = 'gz_v_fa_wall01', type = "pared"}
}

Housing['walls'] = {
    "default",
    "https://cdn.discordapp.com/attachments/953235661220106280/1042689265043255398/R-_1_.png",
    "https://cdn.discordapp.com/attachments/953235661220106280/1042690486755934228/R-_2_.png",
    "https://cdn.discordapp.com/attachments/953235661220106280/1042690951468027936/R.gif",
    "https://cdn.discordapp.com/attachments/984969563890389023/1042691912504709180/ggg.gif"
}

Housing['floors'] = {
    "default", -- Default (NO QUITAR ESTE VALOR)
    "https://media.discordapp.net/attachments/866703522162278420/866705424908812289/wallpaperbetter.com_1920x1080_36.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703553807908894/wallpaperbetter.com_1920x1080.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703663572320256/wallpaperbetter.com_1920x1080_2.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703902777671730/wallpaperbetter.com_1920x1080_6.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703933958258738/wallpaperbetter.com_1920x1080_7.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703998957256744/wallpaperbetter.com_1920x1080_8.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704068893081640/wallpaperbetter.com_1920x1080_10.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704202411933726/wallpaperbetter.com_1920x1080_13.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704410792165387/wallpaperbetter.com_1920x1080_17.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704726094512157/wallpaperbetter.com_1920x1080_20.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704873315368981/wallpaperbetter.com_1920x1080_24.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704904847360030/wallpaperbetter.com_1920x1080_25.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705198125547580/wallpaperbetter.com_1920x1080_31.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705311745310720/wallpaperbetter.com_1920x1080_33.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705480529215488/wallpaperbetter.com_1920x1080_37.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704657723555840/wallpaperbetter.com_1920x1080_19.jpg",
}

Housing['floors'] = {
    "default", -- Default (NO QUITAR ESTE VALOR)
    "https://media.discordapp.net/attachments/866703522162278420/866705424908812289/wallpaperbetter.com_1920x1080_36.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703553807908894/wallpaperbetter.com_1920x1080.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703663572320256/wallpaperbetter.com_1920x1080_2.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703902777671730/wallpaperbetter.com_1920x1080_6.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703933958258738/wallpaperbetter.com_1920x1080_7.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866703998957256744/wallpaperbetter.com_1920x1080_8.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704068893081640/wallpaperbetter.com_1920x1080_10.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704202411933726/wallpaperbetter.com_1920x1080_13.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704410792165387/wallpaperbetter.com_1920x1080_17.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704726094512157/wallpaperbetter.com_1920x1080_20.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704873315368981/wallpaperbetter.com_1920x1080_24.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704904847360030/wallpaperbetter.com_1920x1080_25.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705198125547580/wallpaperbetter.com_1920x1080_31.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705311745310720/wallpaperbetter.com_1920x1080_33.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866705480529215488/wallpaperbetter.com_1920x1080_37.jpg",
    "https://media.discordapp.net/attachments/866703522162278420/866704657723555840/wallpaperbetter.com_1920x1080_19.jpg",
}

Housing['armories'] = {
    'p_cs_locker_01_s',
    'p_cs_locker_02',
    'p_cs_locker_01',
    'prop_cs_lester_crate',
    'prop_champ_box_01',
    'prop_lev_crate_01',
    'v_res_fh_sidebrdlngb',
    'v_res_fh_sidebrddine',
    'v_res_d_sideunit',
    'v_res_mbbedtable',
    'v_res_j_tvstand',
    'v_res_mbdresser',
    'v_res_mbottoman',
    'v_res_mconsolemod',
    'v_res_mcupboard',
    'v_res_mdchest',
    'v_res_msoncabinet',
    'prop_cabinet_02b',
    'v_res_m_armoire',
    'v_res_m_sidetable',
    'v_res_tre_bedsidetable',
    'v_res_tre_smallbookshelf',
    'v_res_tre_storagebox',
    'v_res_tre_storageunit',
    'v_res_m_sidetable',
    'v_res_tre_wdunitscuz',
    'prop_devin_box_closed',
    'prop_mil_crate_01',
    'prop_mil_crate_02',
    'prop_ld_int_safe_01',
    'p_v_43_safe_s',
    'prop_ld_int_safe_01',
    'prop_mil_crate_02',
    'v_res_d_dressingtable',
    'prop_fbibombfile',
    'v_res_cabinet',
    'p_secret_weapon_02',
    'prop_gun_case_02',
    'prop_coffin_02b',
    'apa_mp_h_str_shelffreel_01'
}

Housing['furni'] = {
    ['Categories'] = {
        {'table', 'Mesas'},
        {'chair', 'Sillas'},
        {'storage', 'Almacen'},
        {'decorations', 'Decoración'},
        {'electronics', 'Electrónica'},
        {'Plants', 'Plantas'},
        {'sofa', 'Sofas'},
        {'bed', 'Camas'},
        {'CashGoldJewels', 'Joyas'},
        {'FoodandDrinks', 'Comida y Bebida'},
        {'lights', 'Luces'},
        {'kitchen', 'Cocina'},
        {'bathroom', 'Baño'},
        {'bins', 'Papeleras'},
        {'accessory', 'Miscelánea'},
        {'other', 'Otros'},
    },
    ['chair'] = {
        {'Silla de mesa', 'prop_table_02_chr', 50},
        {'Silla armada', 'prop_cs_folding_chair_01', 150},
        {'Silla rock', 'prop_rock_chair_01', 150},
        {'Silla de ruedas', 'prop_wheelchair_01', 150},
        {'Silla de oficina', 'p_clb_officechair_s', 125},
        {'Silla oficina gris', 'prop_off_chair_04_s', 150},
        {'Silla oficina marrón', 'prop_cs_office_chair', 150},
        {'Silla oficina azul', 'prop_off_chair_04', 150},
        {'Silla oficina gastada', 'prop_off_chair_03', 150},
        {'Silla oficina alta', 'prop_off_chair_01', 150},
        {'Silla oficina baja', 'prop_off_chair_05', 150},
        {'Silla oficina acolchada', 'v_club_officechair', 150},
        {'Silla oficina rigida', 'v_corp_offchair', 150},
        {'Silla de tortura', 'prop_torture_ch_01', 150},
        {'Silla de cocina', 'p_dinechair_01_s', 150},
        {'Silla sol', 'p_soloffchair_s', 150},
        {'Silla yate', 'prop_sol_chair', 150},
        {'Silla', 'prop_chair_02', 150},
        {'Silla aluminio madera', 'prop_chair_01b', 150},
        {'Silla madera', 'prop_chair_04a', 150},
        {'Silla blanca', 'prop_chair_04b', 150},
        {'Silla gastada', 'prop_chair_06', 150},
        {'Silla madera antigua', 'prop_chair_07', 150},
        {'Silla aluminio', 'prop_chair_09', 150},
        {'Silla con estampado', 'prop_chateau_chair_01', 150},
        {'Silla madera clara', 'prop_clown_chair', 150},
        {'Silla cine', 'prop_direct_chair_01', 150},
        {'Silla marrón', 'prop_cs_office_chair', 150},
        {'Silla plastico sucia', 'prop_gc_chair02', 150},
        {'Silla moderna', 'apa_mp_h_din_chair_12', 150},
        {'Silla plastico azul', 'v_ilev_chair02_ped', 150},
        {'Silla oficina rota', 'v_corp_cd_chair', 150},
        {'Silla escritorio gris', 'v_corp_bk_chair3', 150},
        {'Silla de tela', 'prop_skid_chair_03', 150},
        {'Silla madera con apoyos', 'prop_table_01_chr_a', 150},
        {'Silla madera sin apoyos', 'prop_table_01_chr_b', 150},
        {'Silla madera ancha', 'prop_table_02_chr', 150},
        {'Silla plástico', 'prop_table_03_chr', 150},
        {'Silla plástico ancho', 'prop_table_03b_chr', 150},
        {'Silla aluminio con tela', 'prop_table_04_chr', 150},
        {'Silla moderna', 'prop_table_05_chr', 150},
        {'Silla blanca con patas aluminio', 'apa_mp_h_din_chair_04', 150},
        {'Silla blanca con patas abiertas', 'apa_mp_h_din_chair_08', 150},
        {'Sillón de piel', 'apa_mp_h_din_chair_09', 150},
        {'Sillón con cojines', 'apa_mp_h_stn_chairarm_02', 150},
        {'Silla comoda', 'v_ilev_hd_chair', 150},
        {'Silla moderna con cojines', 'apa_mp_h_stn_chairarm_12', 150},
        {'Silla madera con cojin', 'apa_mp_h_stn_chairarm_11', 150},
        {'Silla moderna roja', 'hei_heist_din_chair_02', 150},
        {'Silla moderna gris', 'v_ilev_p_easychair', 150},
        {"Puff rosa", "v_corp_facebeanbag", 70},
        {"Puff morado", "v_corp_facebeanbagb", 70},
        {"Puff gastado", "v_corp_facebeanbagc", 60},
        {"Puff gastado azul", "v_corp_facebeanbagd", 60},
        {"Silla de cuero", "v_corp_lazychair", 50},
        {"Sillon de cuero ancho","v_corp_bk_chair1", 50},
        {"Silla elegante", "v_ilev_m_dinechair", 40},
        {"Silla humilde", "v_res_fa_chair01", 20},
        {"Silla elegante madera","prop_chair_03" , 40},
        {"Silla alcolchada", "v_ret_chair", 80},
        {"Sillón negro", "v_ret_ps_chair", 120},
    },
    ['table'] = {
        {"Mesa Ejecutiva", "v_ilev_liconftable_sml", 120},
        {"Mesa baja negra", "v_res_fh_coftablea", 80},
        {"Mesa baja gris", "v_res_fh_coftableb", 80},
        {"Mesa baja de cristal", "v_res_fh_coftbldisp", 80},
        {"Escritorio básico", "v_corp_maindesk", 80},
        --{'Escritorio', 'v_corp_deskseta', 250},
        {'Escritorio doble pantalla', 'v_corp_desksetb', 250},
        {'Escritorio oscuro doble pantalla', 'v_corp_officedesk', 250},
        {'Escritorio oscuro', 'v_corp_officedesk003', 250},
        {'Escritorio básico oscuro', 'v_corp_officedesk_5', 250},
        {"Mesa redonda", "v_res_m_dinetble_replace", 150},
        {"Mesa alta decorativa", "v_ret_tablesml", 60},
        {"Mesa cristal baja", "prop_t_coffe_table_02", 300},
        {"Mesa de bambu","prop_table_04",60},
        {"Mesa de cristal","v_res_fh_diningtable", 200},
        {"Mesa de crital y aluminio", "apa_mp_h_din_table_11", 150},
        {"Mesa negra", "apa_mp_h_tab_sidelrg_04", 150},
        {"Escritorio enchufe", "v_corp_officedesk_5", 150},
        {'Mesa TV', 'prop_tv_cabinet_03', 500},
        {'Mesa granjera', 'prop_ld_farm_table02', 300},
        {'Mesa granjera sucia', 'prop_ld_farm_table01', 300},
        {'Mesa cafe negra', 'prop_t_coffe_table', 300},
        {'Mesa cafe de cristal', 'prop_t_coffe_table_02', 300},
        {'Tri Mesa', 'prop_tri_table_01', 300},
        {'Mesa Protest', 'prop_protest_table_01', 300},
        {'Mesa moderna pequeña', 'hei_prop_yah_table_01', 150},
        {'Mesa moderna mediana', 'hei_prop_yah_table_02', 150},
        {'Mesa moderna grande', 'hei_prop_yah_table_03', 150},
        {'Mesa 5', 'prop_ld_farm_table01', 150},
        {'Mesa 6', 'prop_ld_farm_table02', 150},
        {'Mesa con mantel rojo', 'prop_chateau_table_01', 150},
        {'Mesa pequeña abierta', 'prop_fbi3_coffee_table', 150},
        {'Mesa pequeña de madera', 'prop_patio_lounger1_table', 150},
        {'Mesa con banco de madera', 'prop_picnictable_01', 150},
        {'Mesa redonda de madera', 'prop_proxy_chateau_table', 150},
        {'Mesa cuadrada de madera', 'prop_rub_table_01', 150},
        {'Mesa rectangular de madera', 'prop_rub_table_02', 150},
        {'Mesa de madera', 'prop_table_01', 150},
        {'Mesa redonda de madera grande', 'prop_table_02', 150},
        {'Mesa de plastico', 'prop_table_03', 150},
        {'Mesa de plastico pequeña', 'prop_table_03b', 150},
        {'Mesa de madera y aluminio', 'prop_table_04', 150},
        {'Mesa moderna redonde', 'prop_table_05', 150},
        {'Mesa antigua', 'prop_table_06', 150},
        {'Mesa de aluminio', 'prop_table_07', 150},
        {'Mesa alta robusta', 'prop_table_08', 150},
        {'Mesa baja robusta', 'prop_table_08_chr', 150},
        {'Mesa plastico sucio', 'prop_ven_market_table1', 150},
        {'Mesa 25', 'v_ilev_liconftable_sml', 150},
        {'Mesa 26', 'prop_table_tennis', 150},
        {'Mesa 27', 'prop_pooltable_02', 150},
        {'Mesa 28', 'prop_astro_table_02', 150},
        {'Mesa 29', 'prop_astro_table_01', 150},
        {"Mesa 30", "apa_mp_h_din_table_01", 80},
        {"Mesa 31", "apa_mp_h_din_table_04", 120},
        {"Mesa 32", "apa_mp_h_yacht_coffee_table_01", 80},
        {"Mesa 33", "apa_mp_h_yacht_coffee_table_02", 80},
        {"Mesa 34", "gr_dlc_gr_yacht_props_table_03", 80},
        {"Mesa 35", "hei_heist_din_table_04", 80},
        {"Mesa 36", "hei_heist_din_table_07", 150},
        {"Mesa 37","prop_yacht_table_03", 200},
        {"Mesa 38", "v_ret_fh_dinetable", 150},
        {'Mesa 39', 'v_ind_dc_table', 150},
        {'Mesa 40', 'v_ind_rc_lowtable', 150},
        {'Mesa 41', 'v_res_d_coffeetable', 150},
        {"Mesa 42", "v_res_d_dressingtable", 80},
        {"Mesa 43", "v_res_d_roundtable", 120},
        {"Mesa 44", "v_res_d_smallsidetable", 80},
        {"Mesa 45", "v_res_j_coffeetable", 80},
        {"Mesa 46", "v_res_j_lowtable", 80},
        {"Mesa 47", "v_res_m_sidetable", 80},
        {"Mesa 48", "v_res_tre_table001", 150},
        {"Mesa 49", "v_ret_fh_kitchtable", 200},
        {"Mesa 50", "prop_yacht_table_01", 120},
        {"Mesa 51", "prop_yacht_table_02", 80},
        {"Mesa 52", "v_med_p_sidetable", 120},
        {"Mesa 53", "ba_prop_int_edgy_table_01", 80},
        {"Mesa 54", "ba_prop_int_edgy_table_02", 80},
        {"Mesa 55", "apa_mp_h_yacht_side_table_02", 80},
        {"Mesa 56", "apa_mp_h_yacht_side_table_01", 80},
        {"Mesa 57", "hei_heist_din_table_06", 150},
        {"Mesa 58", "apa_mp_h_din_table_05", 80},
        {"Mesa 59", "apa_mp_h_din_table_04", 150},
        {"Mesa 60", "apa_mp_h_yacht_side_table_02", 150},
    },


    ['decorations'] = {
        {"Mesa de billar verde", "prop_pooltable_02", 200},
        {"Mesa de billar morada", "prop_pooltable_3b", 200},
        {"Tacos de billar", "prop_pool_rack_02", 100},
        {"Tacos de billar profesional", "prop_pool_rack_01", 100},
        {'Biblioteca pequeña', 'v_corp_bk_lfltstand', 250},
        {'Botella de cristal', 'apa_mp_h_acc_bottle_01', 100},
        {'Conjunto de tres velas', 'apa_mp_h_acc_candles_01', 100},
        {'Espejo pequeño', 'p_int_jewel_mirror', 100},
        {'Plato ceramica decoración', 'apa_mp_h_acc_dec_plate_01', 100},
        {'Jarrón decorativo', 'apa_mp_h_acc_vase_01', 100},
        {'Pack portalapices múltiple', 'v_res_desktidy', 100},
        {'Florero', 'apa_mp_h_acc_vase_flowers_01', 100},
        {'Cenicero dorado', 'ex_prop_ashtray_luxe_02', 100},
        {'Periódico abierto', 'p_cs_newspaper_s', 100},
        {'Folleto', 'p_cs_pamphlet_01_s', 100},
        {'Bong amarillo y rojo', 'prop_bong_01', 100},
        {'Oso de peluche', 'prop_mr_rasberryclean', 100},
        {'Guitarra', 'prop_acc_guitar_01', 100},
        {'Pizzara con plano', 'p_planning_board_04', 100},
        {'Reloj de pared grande', 'prop_big_clock_01', 100},
        {'Reloj de pared grande luminoso', 'prop_egg_clock_01', 100},
        {'Cuadro con caballo blanco', 'v_ilev_ra_doorsafe', 100},
        {'Diana competitiva', 'prop_dart_bd_cab_01', 100},
        {'Diana estándar', 'prop_dart_bd_01', 100},
        {'Bicicleta estática', 'prop_exercisebike', 300},
        {'Pantalones cortos', 'p_laz_j02_s', 300},
        {"Panel acolchado", "v_res_d_paddedwall", 250},
        {"Calavera decorativa", "vw_prop_casino_art_skull_02b", 40},
        {"Estructura metalica", "prop_billb_frame01a", 100},
        {"Alfombra negra", "prop_yoga_mat_02", 50},
        {"Cráneo animal", "v_res_d_ramskull", 100},
        {"Libro marron", "v_res_fa_book01", 20},
        {"Libro morado", "v_res_fa_book02", 20},
        {"Vela grande decorativa", "v_res_m_candle", 40},
        {"Guitarra blanca eléctrica" , "prop_el_guitar_01" , 200},
        {"Atrapasueños", "prop_garden_dreamcatch_01", 50},
        {"Plátano dorado decorativo","ch_prop_ch_trophy_monkey_01a", 50},
        {"Figura pantera", "v_res_sculpt_decf", 50},
        {"Pieza de cuarzo negra", "v_res_fa_crystal01", 20},
        {"Escultura ADN", "v_res_sculpt_decb", 50},
        {"Vela tradicional blanca", "v_res_fa_candle04", 20},
        {"Pesa de 1kg", "prop_freeweight_01", 50},
        {"Satisfier negro", "v_res_d_dildo_a", 250},
        {"Joystick 2", "v_res_d_dildo_f", 250},
        {"Joystick 3", "v_res_d_dildo_b", 250},
        {"Anal Tub", "v_res_d_lube", 250},
        {"Estructura metalica mediana", "prop_billb_frame01b", 100},
        {"Estructura metalica pequeña", "prop_billb_frame04b", 100},
        {"Disco de oro", "hei_heist_acc_artgolddisc_03", 100},
        {"Barriles de cerveza", "vw_prop_vw_barrel_pile_01a", 50},
        {"Barril de vino", "vw_prop_vw_barrel_01a", 50},
        {"Cuadro 1", "v_ilev_ra_doorsafe", 50},
        {"Cuadro Area 51", "vw_prop_vw_wallart_118a", 50},
        {"Cuadro pictogramas rojo", "vw_prop_vw_wallart_94a", 50},
        {"Excultura granada", "vw_prop_casino_art_grenade_01d", 50},
        {"Libros apilados", "vw_prop_book_stack_01b", 50},
        {"Cuadro formas geometricas azules", "vw_prop_vw_wallart_174a", 50},
        {"Cuadros posters peliculas", "vw_prop_vw_wallart_19a", 50},
        {"Cuadro circulo negro", "vw_prop_vw_wallart_55a", 50},
        {"Cuadro anime", "vw_prop_vw_wallart_67a", 50},
        {"Cuadro triangulo con negro", "vw_prop_vw_wallart_90a", 50},
        {"Cuadro pelea", "vw_prop_vw_wallart_72a", 50},
        {"Cuadro negro", "vw_prop_vw_wallart_151d", 50},
        {"Cuadro Sprunk retro", "vw_prop_vw_wallart_107a", 50},
        {"Cuadro donuts", "vw_prop_vw_wallart_138a", 50},
        {"Caja de coleccionistas", "ba_prop_battle_crate_art_02_bc" , 50},
        {"Caja de pintor", "ex_prop_crate_art_bc" , 50},
        {"Caja de esculturas y cuadro", "ex_prop_crate_art_02_sc" , 50},
        {"Cuadro con triangulo", "vw_prop_casino_art_console_02a" , 50},
        {"Escultura de Adam y Eva", "vw_prop_casino_art_statue_02a" , 50},
        {"Coche de coleccionista", "vw_prop_casino_art_car_09a" , 50},
        {"Cuadro pibwasser retro", "vw_prop_vw_wallart_95a" , 50},
        {"Cuadro just dance", "sum_prop_ac_qub3d_poster_01a" , 50},
        {"Cuadro Need for Speed", "ch_prop_ch_wallart_06a", 50},
        {"Cuadro Need for Speed: Hot Pirsuit", "ch_prop_ch_wallart_07a", 50},
        {"Cuadro retro", "ch_prop_ch_wallart_04a", 50},
        {"Cuadro melecoton", "vw_prop_vw_wallart_03a", 50},
        {"Cuadro dibujos", "vw_prop_vw_wallart_124a", 50},
        {"Cuadro manga", "vw_prop_vw_wallart_125a", 50},
        {"Cuadro moderno mujer", "vw_prop_vw_wallart_172a" , 50},
        {"Cuadro abstracto espiral", "vw_prop_vw_wallart_44a" , 50},
        {"Cuadro moderno mujer azul", "vw_prop_vw_wallart_75a" , 50},
        {"Cuadro retro videojuegos", "vw_prop_vw_wallart_129a" , 50},
        {"Panel plantilla tatuajes", "vw_prop_vw_wallart_93a" , 50},
        {"Cuadro poster pelicula", "ch_prop_ch_wallart_07a" , 50},
        {"Cuadro Race and chase", "ch_prop_ch_wallart_09a" , 50},
        {"Cuadro Space monkey 3", "vw_prop_vw_wallart_19a" , 50},
        {"Colección triple peliculas", "vw_prop_vw_wallart_20a" , 50},
        {"Cuadro mapache", "vw_prop_vw_wallart_58a" , 50},
        {"Cuadro moderno pelea", "vw_prop_vw_wallart_72a" , 50},
        {"Servidor tamaño mediano", "v_corp_servercln" , 50},
        {"Servidor tamaño pequeño", "v_corp_servercln2" , 50},
        {"Servidor tamaño grande", "v_corp_servrtwrfd" , 50},
        {"Ventilador de mesa negro", "v_ind_cm_fan" , 50},
        {"Ventilador grande blanco", "v_res_fa_fan" , 50},
        {"Alfombra grande beig","hei_heist_acc_rugwooll_03", 50},
        {"Alfombra plastificada gris","hei_heist_acc_rugwooll_02", 50},
        {"Alfombra mediana marrón y blanca","apa_mp_h_acc_rugwoolm_03", 50},
        {"Alfombra mediana geométrica blanca","apa_mp_h_acc_rugwoolm_04", 50},
        {"Alfombra de felpa grande blanca","apa_mp_h_acc_rugwooll_03", 50},
        {"Alfombra moderna mediana roja y blanca","apa_mp_h_acc_rugwoolm_01", 50},
        {"Alfombra moderna blanca,negra y verde","apa_mp_h_acc_rugwoolm_02", 50},
        {"Alfombra de exteriores","apa_mp_h_acc_rugwools_03", 50},
        {"Alfombra de ducha azul","prop_yoga_mat_01", 50},
        {"Alfombra de ducha roja","p_yoga_mat_03_s", 50},
        {"Cadena metalica","prop_cs_leg_chain_01", 50},
        {"Skate","v_res_skateboard", 50},
        {"Pista de skate pequeña","prop_skate_spiner", 50},
        {"Pista de skate mini rampa","prop_skate_quartpipe_cr", 50},
        {"Pista de skate grande","prop_skate_kickers_cr", 50},
        {"Bolo de colores", "vw_prop_casino_art_bowling_01b", 90},
        {"Jarron grande rojo", "apa_mp_h_acc_vase_02", 90},
        {"Cinta de Correr", "apa_p_apdlc_treadmill_s", 90},
        {"Guantes Boxeo rojo", "prop_boxing_glove_01", 90},
        {"Katana", "prop_cs_katana_01", 90},
        {"Calavera decorativa", "v_ret_ta_skull", 90},
        {"Calavera 2", "vw_prop_casino_art_skull_02b", 90},
        {"Craneo decorativo", "xs_prop_trinket_skull_01a", 90},
        {"Calavera decorativa blanca", "vw_prop_casino_art_skull_03a", 90},
        {"Maqueta 3D Los Santos", "ex_office_citymodel_01", 90},

    },
    ['electronics'] = {
        {'TV Plana', 'prop_tv_flat_02', 750},
        {'TV Plana grande', 'prop_tv_flat_01', 550},
        {'TV gorda', 'prop_tv_06', 350},
        {'TV gorda pequeña', 'prop_tv_02', 250},
        {'TV Plana media', 'xm_prop_x17_tv_flat_01', 250},
        {'TV Plana enorme', 'vw_prop_vw_cinema_tv_01', 250},
        {'Radio blanca', 'prop_portable_hifi_01', 100},
        {'Torre pc', 'prop_dyn_pc_02', 500},
        {'Torre PC viejo', 'prop_pc_01a', 100},
        {'Monitor', 'prop_monitor_01c', 75},
        {'Monitor gris', 'prop_ld_monitor_01', 75},
        {'Monitor antiguo', 'prop_monitor_03b', 25},
        {'Movil', 'p_amb_phone_01', 75},
        {'Movil viejo', 'prop_v_m_phone_o1s', 75},
        {'Telefono de oficina', 'prop_office_phone_tnt', 75},
        {'Telefono blanco', 'prop_cs_phone_01', 75},
        {'Tablet', 'prop_cs_tablet_02', 75},
        {'Micro', 'prop_table_mic_01', 75},
        {'Portatil', 'p_amb_lap_top_02', 75},
        {'Portatil 2', 'p_cs_laptop_02', 75},
        {'Portatil gaming', 'xm_prop_x17_laptop_lester_01', 75},
        {'Portatil cerrado', 'p_cs_laptop_02_w', 75},
        {'Panel blanco', 'prop_ld_keypad_01b', 75},
        {'Panel gris', 'prop_ld_keypad_01', 75}, 
        {'PC', 'prop_dyn_pc', 75},
        {'Torre PC negro', 'hei_prop_heist_pc_01', 75}, 
        {'Torre PC pequeña Gris', 'prop_pc_02a', 75},
        {'Raton negra', 'prop_cs_mouse_01', 75},
        {'Raton gris', 'prop_mouse_01a', 75},
        {'Raton con alfombrilla', 'v_res_mousemat', 75},
        {'Teclado negro', 'hei_prop_hei_cs_keyboard', 75},
        {'Teclado negro grande', 'prop_cs_keyboard_01', 75},
        {'Teclado blanco', 'prop_keyboard_01a', 75},
        {'Reloj de mesa', 'v_res_fh_bedsideclock', 75},
        {"Altavoz con movil", "v_res_fh_speakerdock", 50},
        {"Mando consola", "prop_controller_01", 50},
        {"Portátil", "p_amb_lap_top_02", 200},
        {"Altavoz grande", "prop_speaker_03", 40},
        {"Panel seguridad", "v_corp_bk_secpanel", 400},
        {"Monitor pequeño","prop_ld_monitor_01" , 100},
        {"Ventilador", "v_res_fh_towerfan", 80},
        {"Ordenador moderno", "ba_prop_battle_club_computer_02", 200},
        {"Pantalla de techo", "xm_prop_x17_tv_ceiling_01", 200},
        {"Setup básico", "v_corp_desksetb", 500},
        {"Tablet negra", "hei_prop_dlc_tablet", 200},
        {"Mueble TV Grande", "apa_mp_h_str_avunitl_01_b", 200},
        {"Mueble TV", "apa_mp_h_str_avunits_01", 500},
        {"Mueble TV con altavoces", "apa_mp_h_str_avunitm_03", 200},
    },
    ['bed'] = {
        {'Cama de matrimonio desecha', 'v_res_msonbed_s', 450}, 
        {'Cama descuidada', 'p_lestersbed_s', 150},
        {'Cama de matrimonio suite', 'p_mbbed_s', 150}, 
        {'Cama antiguo desecha', 'p_v_res_tt_bed_s', 150},
        {"Cama moderna", "apa_mp_h_bed_double_08", 350},
        {"Cama triple", "apa_mp_h_bed_wide_05", 350},
        {"Cama de matrimonio clasica", "apa_mp_h_bed_with_table_02", 350},
        {"Cama moderna", "hei_heist_bed_double_08", 350},
        {"Sofá cama", "ex_prop_exec_bed_01", 350},
        {"Cama antigua", "v_res_d_bed", 200},
        {"Cama individual desecha", "v_res_lestersbed", 200},
        {"Cama moderna suite", "apa_mp_h_bed_double_09", 250},
        {"Cama triple suite", "apa_mp_h_yacht_bed_02", 350},
        {"Cama individual", "gr_prop_bunker_bed_01", 350},

    },
    ['sofa'] = {
        {'Sofa de fábrica', 'p_res_sofa_l_s', 225},
        {"Sofa moderno pequeño" , "v_res_d_sofa" , 80},
        {'Sofa moderno blanco', 'prop_t_sofa', 300}, 
        --{'Sofa blanco de L', 'p_lev_sofa_s', 150},
        {'Sofa gris grande', 'apa_mp_h_stn_sofacorn_01', 300},
        {'Sofa de cuero', 'p_v_med_p_sofa_s', 150},
        {'Sillon verde con rallas', 'p_yacht_sofa_01_s', 150},
        {'Sofa Blanco de L', 'v_ilev_m_sofa', 150},
        {'Sofa pequeño azul', 'v_res_tre_sofa_s', 150},
        {'Sofa roto', 'prop_rub_couch02', 150},
        {'Sofa roto 2', 'v_tre_sofa_mess_a_s', 150},
        {'Sofa sucio', 'v_tre_sofa_mess_b_s', 150},
        {'Sofa sucio 2', 'v_tre_sofa_mess_c_s', 150},
        {'Sillon Sucio', 'prop_ld_farm_chair01', 150},
        {'Sofa de Tela', 'prop_ld_farm_couch01', 150},
        {'Sofa de Tela 2', 'prop_ld_farm_couch02', 150},
        {'Sofa moderno grande', 'apa_mp_h_stn_sofacorn_09', 150},
        {'Sofa blanco moderno', 'apa_mp_h_stn_sofacorn_10', 225},
        {'Sofa elegante marron', 'apa_mp_h_yacht_sofa_01', 225}, 
        {'Sofa gris', 'bkr_prop_clubhouse_sofa_01a', 300},
        {'Sofa azul claro', 'ex_mp_h_off_sofa_003', 300}, 
        {'Sofa azul oscuro', 'ex_mp_h_off_sofa_02', 150},
        {'Sofa de tela marron', 'hei_heist_stn_sofa3seat_02', 150},
        {'Sofa gris claro', 'hei_heist_stn_sofa3seat_06', 150},
        {'Sillon naranja', 'apa_mp_h_stn_chairarm_01', 150},
        {'Sillon rosa', 'apa_mp_h_stn_chairarm_23', 150},
        {'Silla gris', 'apa_mp_h_stn_chairarm_24', 150},
        {'Sillon naranja grande', 'apa_mp_h_stn_chairarm_25', 150},
        {'Sillon naranja fuerte', 'apa_mp_h_stn_chairstrip_01', 150},
        {'Sillon rojo', 'apa_mp_h_stn_chairstrip_02', 150},
        {'Sillon blanco', 'apa_mp_h_stn_chairstrip_05', 150},
        {'Sillon negro', 'apa_mp_h_stn_chairstrip_07', 150},
        {'Sillon marron claro', 'apa_mp_h_yacht_armchair_01', 150},
        {'Sillon negro', 'bkr_prop_clubhouse_armchair_01a', 150},
        {'Sillon blanco', 'ex_mp_h_stn_chairstrip_011', 150},
        {'Silla elegante', 'ex_prop_offchair_exec_04', 150},
        {'Silla morado claro', 'hei_heist_stn_chairarm_04', 150},
        {'Silla blanca elegante', 'p_armchair_01_s', 150},
        {'Silla moderna', 'apa_mp_h_stn_sofa_daybed_02', 150},
        {'Sofa blanco moderno', 'apa_mp_h_stn_sofa2seat_02', 150},
        {'Silla gris largo', 'xm_lab_sofa_02', 150},
        {'Sofa blanco moderno 2', 'xm_lab_sofa_01', 150},
        {'Silla de cuero', 'prop_waiting_seat_01', 150},
        {'Posa pie gris', 'apa_mp_h_stn_foot_stool_01', 150},
        {'Posa pie blanco', 'apa_mp_h_stn_foot_stool_02', 150},
        {'Sofa 48', 'miss_rub_couch_01', 225}, 
        {'Sillon Negro', 'h4_prop_battle_poster_promo_03', 300},
        {"Sofá casual", "sum_mp_h_yacht_sofa_01", 180},
        {"Banco cuero", "prop_wait_bench_01", 100},
        {"Sofá moderno", "prop_t_sofa_02", 180},

    },
    ['Plants'] = {
        {'Planta grande en jarron decorativo', 'p_int_jewel_plant_02', 100},
        {'Planta pequeña en jarron decorativo', 'p_int_jewel_plant_01', 100},
        {'Palmera decorativa', 'prop_fbibombplant', 100},
        {'Bonsái', 'prop_fib_plant_01', 100},
        {'Plantas variadas con flores', 'prop_fib_plant_02', 100},
        {'Planta 7', 'prop_ld_planter2b', 100},
        {'Esquinera', 'prop_plant_int_01a', 100},
        {'Planta de tronco decorativa', 'prop_plant_int_01b', 100},
        {'Planta de tronco en maceta de madera', 'prop_plant_int_02a', 100},
        {'Planta redonda en jarron elegante', 'prop_plant_int_02b', 100},
        {'Planta redonda en maceta regular', 'prop_plant_int_03a', 100},
        {'Planta de hojas alargadas en jarron elegante', 'prop_plant_int_04b', 100},
        {'Palmera', 'prop_plant_int_04a', 100},
        {'Varias palmeras decorativas', 'prop_plant_int_04c', 100},
        {'Bonsái', 'prop_plant_palm_01a', 100},
        {'Planta pequeña decorativa', 'prop_plant_palm_01c', 100},
        {'Planta grande en maceta de arcilla', 'prop_pot_plant_01b', 100},
        {'Planta decorativa en maceta de piedra', 'prop_pot_plant_01a', 100},
        {'Planta decorativa de hojas caidas', 'prop_pot_plant_01c', 100},
        {'Planta grande en maceta de arcilla', 'prop_pot_plant_01d', 100},
        {'Planta de hojas caídas en maceta de arcilla', 'prop_pot_plant_03c', 100},
        {'Planta con flores en copa de jardín', 'prop_pot_plant_05a', 100},
        {"Planta enrredadera", "v_res_ivy", 20},
        {"Planta decorativa", "v_res_fa_plant01", 50},
        {"Planta tropical", "ex_mp_h_acc_plant_palm_01", 20},
        {"Planta Sansevieria", "v_res_mplanttongue", 20},
        {"Planta con fruto", "v_res_mvasechinese", 20},
        {"Cactus decorativo en maceta de piedra","vw_prop_casino_art_plant_10a" , 30},
        {"Planta de interiores en maceta de piedra", "prop_plant_int_03c", 20},
        {"Planta pequeña de hojas caidas", "prop_plant_int_04a", 20},
        {"Planta pared", "prop_pot_plant_6b", 20},
        {"Lirios", "v_ret_ps_flowers_01", 20}
    },
    ['CashGoldJewels'] = {
        {'Maletín de dinero', 'prop_cash_case_02', 50},
        {'Palet con fajos de billetes', 'prop_cash_crate_01', 50},
        {'Palet con fajos de billetes 3', 'hei_prop_cash_crate_half_full', 50},
        {'Billete', 'prop_anim_cash_note_b', 50},
        {'Fajo de billetes', 'prop_anim_cash_pile_01', 50},
        {'Carro metálico con dinero', 'prop_cash_trolly', 50},
        {'Bolsa con dinero', 'prop_poly_bag_money', 50},
        {'Carro azul con lingotes de oro', 'prop_gold_trolly_full', 50},
        {'Carro metálico', 'prop_gold_trolly', 50},
        {'Lingote de oro', 'prop_gold_bar', 50},
        {'Carro grande con lingotes de oro', 'prop_large_gold', 50},
        {'Carro grande con lingotes de oro 2', 'p_large_gold_s', 50},
        {'Estructura de madera con lingotes de oro', 'prop_ld_gold_chest', 50},
        {'Estructura pequeña de oro', 'prop_peyote_gold_01', 50},
        {'Reloj en estuche', 'prop_jewel_03b', 50}, 
        {'Estuche de relojes', 'prop_jewel_04b', 50},
        {'Reloj en estuche 2', 'prop_jewel_02b', 50},
        {'Estuche de anillos', 'prop_jewel_pickup_new_01', 50},
        {'Caja de cartón con cervezas', 'prop_cs_beer_box', 50},
        {"Cajas reforzadas en palet", "p_secret_weapon_02", 300},
        {"Contador de billetes", "bkr_prop_money_counter", 250},
        {"Caja fuerte abierta","h4_prop_h4_safe_01b", 300},
        {"Carrito con cajas de madera", "gr_prop_gr_cage_01a", 200},
        {"Caja fuerte cerrada","h4_prop_h4_safe_01a", 300},
        {"Bidón vacío grafiteado","prop_bin_beach_01d" , 30},
        {"Palet azul con decoración", "sm_prop_smug_crate_m_antiques" , 700},
        {"Palet de madera con decoración", "ex_prop_crate_narc_sc" , 700},
        {"Palet azul con arma dorada", "ex_prop_crate_minig" , 700},
        {"Palet de madera con medicación", "ex_prop_crate_med_sc" , 700},
        {"Palet de madera con maletas", "ex_prop_crate_clothing_bc" , 700},
        {"Caja estructura metálica", "ex_prop_adv_case_sm_02" , 700},
        {"Caja táctica verde", "ex_prop_adv_case" , 700},
        {"Estructura de cajas apiladas", "prop_mb_cargo_01a" , 700},
        {"Caja de madera con cerradura", "prop_box_wood05a" , 700},
        {"Caja de madera verde gastada", "prop_box_wood02a_pu" , 700},
        {"Mesa con marihuana",  "bkr_prop_weed_table_01a", 700},
        {"Fajos de billetes",  "bkr_prop_bkr_cashpile_01", 100},
        {"Paquetes sospechosos",  "bkr_prop_coke_cut_02", 600},
        {'Paquetes de droga', 'bkr_prop_coke_cut_01', 300},
        {'Cuenco con droga', 'bkr_prop_coke_fullmetalbowl_02', 300},
        {'Vaso con droga', 'bkr_prop_coke_mixtube_03', 300},
        {'Fajos de billetes 2', 'bkr_prop_bkr_cashpile_01', 300},
        {'Pesa con droga', 'bkr_prop_coke_scale_03', 300},
        {'Mesa con droga', 'bkr_prop_coke_table01a', 300},
        {'Paquete con marihuana', 'bkr_prop_weed_bigbag_open_01a', 300},
        {'Planta de marihuana', 'bkr_prop_weed_drying_02a', 300},
        {'Mesa con droga 2', 'bkr_prop_meth_table01a', 300},
        {'Fajos de billetes 3', 'bkr_prop_bkr_cashpile_01', 300},
        {'Maletín negro', 'bkr_prop_biker_case_shut', 300},
        {'Maletín con armas', 'bkr_prop_biker_gcase_s', 300},
        {'Cajas de munición', 'ex_office_swag_guns02', 300},
        {'Caja de madera grande con armas largas', 'ex_office_swag_guns04', 300},
        {'Pizarra con plan', 'ch_prop_whiteboard_04', 300},
        {'Caja de madera con dos cerraduras', 'gr_prop_gr_rsply_crate03a', 300},
        {'Caja metálica granate abierta', 'gr_prop_gr_tool_chest_01a', 300},
        {'Caja metálica granate cerrada', 'gr_prop_gr_tool_draw_01a', 300},
        {'Aparador metálico granate', 'gr_prop_gr_tool_draw_01d', 300},
        {'Cajonera metálica granate', 'gr_prop_gr_tool_draw_01b', 300},
        {'Silueta rígida de tiro', 'gr_prop_gr_target_05a', 300},
        {'Caja de madera sin tapa', 'gr_prop_gr_bulletscrate_01a', 300},
        {'Silueta rígida de tiro desgastada', 'gr_prop_gr_target_04a', 300},
        {'Caja de madera oscurecida con armas largas', 'ex_office_swag_guns04', 300},
        {'Estructura de cristal con armas', 'vw_prop_casino_art_gun_02a', 300},
        {"Cuadro figuras rosas" ,"vw_prop_vw_wallart_94a" , 50},
        {'Caja cerrada de armas', 'prop_box_guncase_03a', 300},
        {"Caja de munición" ,"prop_box_ammo07b" , 50},
        {"Armario táctico",  "xm_prop_xm_gunlocker_01a", 600},
        {"Emblema de The Lost","prop_mk_bike_logo_1", 50},
    },

    ['other'] = {
        {'Muro blanco de ladrillos', 'xs_prop_arena_wall_02a_sf', 300},
        {'Cristal gris transparente', 'v_ilev_go_window', 300},
        {'Persianas', 'prop_fib_broken_window_3', 300},
        {'Ventana con persianas blancas', 'v_ilev_cor_windowsolid', 300},
        {'Conducto de ventilación negro', 'prop_wall_vent_01', 300},
        {'Puerta de contenedor de carga verde', 'prop_container_door_mb_r', 300},
        {'Puerta de contenedor de carga verde 2', 'prop_container_door_mb_l', 300},
        {'Taburete ', 'h4_prop_int_edgy_stool', 300},
        {'Televisión rectangular', 'ba_prop_battle_club_screen_02', 300},
        {'Portátil', 'ba_prop_club_laptop_dj', 300},
        {'Cristal gris transparente 2', 'bkr_prop_rt_clubhouse_wall', 300},
        {'Persianas con rayas verdes', 'h4_prop_battle_club_screen', 300},
        {'Lámpara de techo cromada', 'h4_prop_casinoclub_lights_domed', 300},
        {'Lámpara de techo reflejo', 'bkr_prop_biker_pendant_light', 300},
        {'Pizarra con garabatos', 'ch_prop_whiteboard_04', 300},
        {'Muñeca niña rosa', 'ch_prop_princess_robo_plush_07a', 300},
        {'Muñeco gato naranja', 'ch_prop_arcade_claw_plush_05a', 300},
        {'Muñeco gato rosa', 'ch_prop_arcade_claw_plush_01a', 300},
        {'Muñeco gato naranja', 'ch_prop_arcade_claw_plush_04a', 300},
        {'Muñeco gato azul celeste', 'ch_prop_arcade_claw_plush_03a', 300},
        {'Muñeco gato rojo', 'ch_prop_arcade_claw_plush_06a', 300},
        {'Muñeca niña pelo verde', 'ch_prop_shiny_wasabi_plush_08a', 300},
        {'Máquina recreativa morada', 'ch_prop_arcade_degenatron_01a', 300},
        {'Máquina recreativa roja', 'ch_prop_arcade_penetrator_01a', 300},
        {'Máquina recreativa azul', 'ch_prop_arcade_street_01d_off', 300},
        {'Máquina recreativa rosa', 'ch_prop_arcade_street_01b', 300},
        {'Cartel pequeño congelados', 'ch_prop_arc_love_btn_ice', 300},
        {'Mantel con plato y cubiertos', 'v_res_fh_tableplace', 300},


    },


    ['FoodandDrinks'] = {
        {'Cacahuetes', 'prop_peanut_bowl_01', 50},
        {'Bol', 'prop_cs_bowl_01', 50}, 
        {'Vaso de plástico', 'prop_cs_bs_cup', 50},
        {'Cafe', 'p_ing_coffeecup_02', 50},
        {'Puesta de Sandia', 'prop_fruit_stand_03', 50},
        {'Puesta de naranja', 'prop_fruit_stand_02', 50},
        {'Puesto de Fruta', 'prop_fruit_stand_01', 50},
        {'Cajas de cerveza', 'prop_cs_beer_box', 50},
        {'Cervezas', 'beerrow_world', 50},
        {'Cerveza', 'prop_amb_beer_bottle', 50},
        {'Cerveza 2', 'prop_beer_blr', 50},
        {'Cerveza 3', 'prop_beer_logger', 50},
        {'Bolsa de hamburguesa', 'ng_proc_food_bag01a', 50},
        {'Hamburguesa', 'prop_food_bs_burg1', 50},
        {'Hamburguesa 2', 'prop_food_bs_burg3', 50},
        {'Patatas', 'prop_food_bs_chips', 50},
        {'Mini hamburguesas', 'prop_food_bs_burger2', 50},
        {'Vaso de Coke', 'prop_food_bs_coffee', 50},
        {'Vasos de Coke', 'prop_food_cups1', 50},
        {'Vasos de Chiken', 'prop_food_cb_cups01', 50},
        {'Vasos de Chiken Grande', 'prop_food_cb_cups02', 50},
        {'Vasos de Coke Grande', 'prop_food_bs_cups02', 50},
        {'Plato de comida', 'prop_cs_plate_01', 50},
        {'Bol de Fideos', 'prop_ff_noodle_01', 50}
    },
    ['lights'] = {
        {'Luz antigua', 'hei_prop_hei_bnk_lamp_02', 150},
        {'Luz de emergencia', 'prop_ld_cont_light_01', 150},
        {'Luz de mesita', 'hei_prop_hei_bnk_lamp_01', 150},
        {'Luz moderna', 'prop_chall_lamp_02', 150},
        {'Luz de cama', 'v_ilev_fh_lampa_on', 150},
        {'Luz vintage', 'prop_construcionlamp_01', 150},
        {'Luz de comedor', 'hei_prop_bank_ornatelamp', 150},
        {'Foco ultravioleta', 'prop_kino_light_03', 150},
        {'Luz de techo', 'prop_oldlight_01c', 150},
        {'Luz 10', 'prop_recycle_light', 150},
        {'Foco cuadruple', 'prop_studio_light_01', 150},
        {'Foco unico', 'prop_studio_light_02', 150},
        {'Luz 13', 'hei_prop_bank_ornatelamp', 150},
        {'Foco pequeño', 'prop_wall_light_02a', 150},
        {'Luz pequeña', 'prop_wall_light_03a', 150},
        {'Luz de metal', 'prop_wall_light_04a', 150},
        {'Luz de cristal', 'prop_wall_light_05a', 150},
        {'Luz de cristal grande', 'prop_wall_light_05c', 150},
        {'Luz colgante', 'v_res_fh_floorlamp', 150},
        {'Mesa alrgada', 'v_ind_cm_light_on', 150},
        {'Ventilador con luz', 'v_med_p_fanlight', 150},
        {'Luz de pared', 'prop_oldlight_01b', 150},
        {'Luz colgante de cristal', 'prop_wall_light_12', 150},
        {'Luz de pared pequeña', 'prop_wall_light_14a', 150},
        {'Luz de jardin', 'prop_wall_light_14b', 150},
        {'Luz de tela', 'apa_mp_h_lit_lightpendant_01', 150},
        {'Luz triple', 'apa_mp_h_lit_lightpendant_05', 150},
        {'Luz de madera triple', 'apa_mp_h_lit_lightpendant_05b', 150},
        {'Luz Gris', 'bkr_prop_biker_pendant_light', 150},
        {'Bombilla', 'xs_prop_arena_lights_ceiling_l_a', 150},
        {'Luz colgante', 'xs_prop_arena_lights_ceiling_l_c', 150},
        {'Luz de baño', 'xs_prop_arena_lights_wall_l_a', 150},
        {'Luz pequeña ', 'xs_prop_arena_lights_wall_l_c', 150},
        {'Luz con mesita', 'xs_prop_x18_hangar_light_a', 150},
        {'Luz de campana', 'xs_prop_x18_hangar_light_b', 150},
        {'Luz elegante colgante', 'h4_prop_battle_lights_ceiling_l_b', 150},
        {'Luz violeta', 'h4_prop_battle_lights_wall_l_b', 150},
        {'Luz de mesita de cama', 'apa_mp_h_lit_lamptablenight_24', 150},
        {'Luz 39', 'apa_mp_h_lit_lightpendant_05b', 150},
        {"Flexo de escritorio" , "v_res_desklamp", 50},
        {"Lámpara de pared", "v_ilev_fh_lampa_on", 50},
        {"Lámpara de pie", "v_res_m_lampstand", 80},
        {"Lámpara humilde", "v_res_fa_lamp1on", 40},
        {"Luz verde", "prop_runlight_g", 70},
        {"Luz roja", "prop_runlight_r", 70},
        {"Luz azul", "prop_runlight_b", 70},
        {"Luz amarilla", "prop_runlight_y", 70},
        {"Luz salón", "apa_mp_h_lit_floorlamp_17", 90},
        {"Neon 1", "v_ret_neon_baracho", 50},
        {"Neon 2", "v_ret_neon_blarneys", 50},
        {"Neon 3", "v_ret_neon_logger", 50},
        {"Neon 4", "prop_beer_neon_01", 50},
        {"Neon 5", "prop_beer_neon_02", 50},
        {"Neon 6", "prop_beer_neon_03", 50},
        {"Neon 7", "prop_beer_neon_04", 50},
        {"Lámpara de pie", "v_res_m_lampstand", 80},
        {"Fluorescente morado", "xs_prop_arena_lights_tube_l_a", 40},
        {"Fluorescente rosa", "xs_prop_arena_lights_tube_l_b", 40},
        {"Columna luz", "apa_mp_h_lit_floorlamp_13", 90},
        {"Fluorescente", "xm_prop_base_tripod_lampc", 40},
        {"Ojo de buey", "xm_prop_lab_floor_lampa", 20},
        {"Foco industrial","prop_worklight_04b" , 90} 

    },

    ['kitchen'] = {
        {'Máquina de cafe', 'apa_mp_h_acc_coffeemachine_01', 150},
        {'Escala', 'bkr_prop_coke_scale_01', 150},
        {'Contenedor azul celeste', 'hei_heist_kit_bin_01', 150},
        {'Aparador marrón', 'hei_heist_str_sideboardl_03', 150},
        {'Carrito gris con ruedas', 'hei_prop_hei_cash_trolly_03', 150},
        {'Bolsa para llevar', 'hei_prop_hei_paper_bag', 150},
        {'Mostrador marrón con luces', 'p_new_j_counter_02', 150},
        {'Bandeja de fruta', 'apa_mp_h_acc_fruitbowl_01', 150},
        {'Plato de frutas', 'apa_mp_h_acc_fruitbowl_02', 150},
        {'Bandeja de frutas en rodajas', 'prop_bar_fruit', 150},
        {'Plato de frutas 2', 'prop_bar_lemons', 150},
        {'Cubo de frutas', 'prop_bar_measrjug', 150},
        {'Fregadero', 'prop_bar_sink_01', 150},
        {'Cuchillo de carnicero', 'prop_cleaver', 150},
        {'Taburete de cocina', 'v_ilev_fh_kitchenstool', 150},
        {'Frigorífico normal blanco sucio', 'prop_trailr_fridge', 150},
        {'Frigorífico largo gris', 'prop_fridge_01', 150},
        {'Frigorífico normal blanco', 'prop_fridge_03', 150},
        {'Nevera de venta de bebida', 'prop_vend_fridge01', 150},
        {'Máquina expendedora de comida', 'prop_vend_snak_01', 150},
        {'Máquina de café', 'prop_vend_coffe_01', 150},
        {'Máquina expendedora roja de bebida', 'prop_vend_soda_01', 150},
        {'Máquina expendedora verde de bebida', 'prop_vend_soda_02', 150},
        {'Máquina expendedora de agua y hielo azul', 'prop_vend_water_01', 150},
        {'Máquina de agua', 'prop_watercooler', 150},
        {"Taza negra", "prop_mug_01", 10},
        {"Rollo de papel", "prop_toilet_roll_02", 30},
        {"Set de cuchillos de pared para la cocina","v_res_mkniferack" , 65},
        {"Nevera cerveza", "prop_bar_fridge_03", 150},
        {"Lavadora blanca", "prop_washer_02" , 75},
        {"Microondas","prop_micro_02" , 50},
        {"Cereales", "v_res_fa_cereal01", 10},
        {"Pizza", "v_ret_fh_pizza01", 30},
        {"Vaso de café", "p_ing_coffeecup_02", 10},
        {"Noodles", "v_res_fa_potnoodle", 20},
        {"Fogones y horno", "prop_cooker_03", 20},
        {"Mueble gris cocina", "prop_ff_counter_01", 20},
        {"Set de cuchillos", "prop_knife_stand", 20},
        {"Microondas de madera", "prop_micro_04", 20},
        {"Set de cazuelas colgadas", "prop_pot_rack", 20},
        {"Tostadora", "prop_toaster_01", 20},
        {"Cuenco blanco y azul", "ex_mp_h_acc_bowl_ceramic_01", 20},
        {"Frigorífico grande gris", "v_res_fridgemodsml", 20},
        {"Set de cubiertos grandes", "prop_utensil", 20},
        {"Cuenco de fruta", "v_res_m_woodbowl", 20},
        {"Tabla de madera para cocina", "v_res_fa_chopbrd", 20},
        {"Frigorífico gigante gris", "v_res_fridgemoda", 20},
        {"Mármol gris", "prop_griddle_01", 20},



    },
    ['bathroom'] = {
        {'Toalla', 'prop_shower_towel', 150},
        {'Toalla 2', 'p_shower_towel_s', 150},
        {'Toalla 3', 'v_res_mbtowel', 150},
        {'Toalla 4', 'v_res_mbtowelfld', 150},
        {'Estante de baño', 'prop_shower_rack_01', 150},
        {'Baño', 'v_res_mbath', 150},
        {'Bañera blanca', 'apa_mp_h_bathtub_01', 150},
        {'Contador', 'p_new_j_counter_02', 150},
        {'Loción1', 'prop_beach_lotion_01', 150},
        {'Loción2', 'prop_beach_lotion_02', 150},
        {'Loción3', 'prop_beach_lotion_03', 150},
        {'Clippers', 'prop_clippers_01', 150},
        {'Inodoro 1', 'prop_toilet_01', 150},
        {'Inodoro 2', 'prop_ld_toilet_01', 150},
        {'Jabón', 'prop_soap_disp_01', 150},
        {'Lavabo 1', 'prop_sink_02', 150},
        {'Lavabo 3', 'prop_sink_04', 150},
        {'Lavabo 4', 'prop_sink_05', 150},
        {'Lavabo 5', 'prop_sink_06', 150},
        {'Lavabo 6', 'v_res_mbsink', 150},
        {'Seca manos', 'prop_handdry_01', 150},
        {'Seca manos 2', 'prop_handdry_02', 150},
        {"Retrete blanco", "prop_toilet_01", 80},
        {"Rollo de papel", "prop_toilet_roll_02", 30},

    },
    ['bins'] = {
        {'Papelera cubo', 'prop_cs_bin_02', 100},
        {'Papelera grande', 'prop_cs_bin_03', 100},
        {'Papelera pequeña', 'prop_fbibombbin', 100},
        {'Bolsa basura', 'prop_rub_binbag_sd_01', 100},
        {'Papelera cuadrada', 'prop_bin_11a', 150},
        {'Papelera con tapadera', 'prop_bin_04a', 150},
        {'Papelera metal', 'prop_bin_07a', 150},
        {'Papelera vintage', 'prop_bin_06a', 150},
        {'Papelera moderna', 'prop_bin_10b', 150},
        {'Papelera plastico', 'prop_bin_11b', 150},
        {'Papelera con ruedas', 'prop_bin_13a', 150},
    },
    ['storage'] = {
        {'Maletín', 'bkr_prop_biker_case_shut', 300},
        {'Taquilla', 'p_cs_locker_02', 300},
        {'Armario blanco', 'v_res_tre_wardrobe', 300},
        {'Taquilla verde', 'v_ind_rc_locker', 300},
        {'Puerta de taquilla gris', 'p_cs_locker_door_01', 300},
        {'Puerta de taquilla azul', 'p_cs_locker_door_02', 300},
        {'Taquilla marron', 'ch_prop_ch_service_locker_01b', 300},
        {'Armero', 'bkr_prop_gunlocker_01a', 300},
        {'Archivador', 'v_corp_bk_filecab', 300},
        {'Armario marron', 'v_corp_bk_filedraw', 300},
        {'Archivador blanco', 'v_corp_deskdraw', 300},
        {'Archivador negro', 'v_corp_deskdrawdark01', 300},
        {'Armario morado', 'apa_mp_h_bed_chestdrawer_02', 300},
        {'Armario marron', 'hei_heist_bed_chestdrawer_04', 300},
        {'Armario moderno', 'apa_mp_h_str_shelffloorm_02', 300},
        {'Estantería negra', 'v_corp_cabshelves01', 300},
        {'Cajonera', 'apa_mp_h_str_sideboardl_11', 300},
        {'Estantería marron', 'apa_mp_h_str_shelfwallm_01', 300},
        {'Estantería de metal', 'v_ind_cf_shelf', 300},
        {'Estantería blanca grande', 'apa_mp_h_str_shelffreel_01', 300},
        {'Repetido', 'apa_mp_h_str_sideboardl_11', 300},
        {'Cómoda de madera', 'apa_mp_h_str_sideboardm_02', 300},
        {'Cómoda moderna', 'apa_mp_h_str_sideboardm_03', 300},
        {'Cómoda moderna azul', 'apa_mp_h_str_sideboards_01', 300},
        {'Cesta azul', 'prop_cs_lester_crate', 150},
        {'Caja de carton', 'prop_champ_box_01', 225},
        {'Comoda de madera grande', 'v_res_fh_sidebrdlngb', 225},
        {'Cómoda azul grande', 'v_res_fh_sidebrddine', 225},
        {'Cajonera de madera', 'v_res_d_sideunit', 225},
        {'Soporte TV', 'v_res_j_tvstand', 225},
        {'Repisa de madera', 'v_res_mbdresser', 225},
        {'Botomana', 'v_res_mbottoman', 225},
        {'Comoda Rustica', 'v_res_mconsolemod', 225},
        {'Comoda rustica grande', 'v_res_mcupboard', 225},
        {'Archivador blanco', 'prop_cabinet_02b', 225},
        {'Repisa blanca', 'prop_cabinet_01b', 225},
        {'Armario', 'v_res_m_armoire', 225},
        {'Mesa cama', 'v_res_tre_bedsidetable', 225},
        {'Estante', 'v_res_tre_smallbookshelf', 225},
        {'Caja', 'v_res_tre_storagebox', 225},
        {'Comoda blanca', 'v_res_tre_storageunit', 225},
        {'Armario de madera', 'v_res_tre_wdunitscuz', 225},
        {'Caja azul', 'prop_devin_box_closed', 225},
        {'Caja de armas', 'prop_mil_crate_01', 225},
        {'Caja de armas pequeño', 'prop_mil_crate_02', 225},
        {'Caja fuerte', 'prop_ld_int_safe_01', 225},
        {'Archivador', 'p_v_43_safe_s', 225},
        {'Repisa Rustica', 'prop_fbibombfile', 225},
        {'Maletin de arma', 'p_secret_weapon_02', 225},
        {'Caja de arma', 'prop_gun_case_02', 225},
        {'Ataúd', 'prop_coffin_02b', 225},
        {"Estantería oficina", "v_corp_offshelfdark", 150},
        {"Cajonera blanca", "v_res_mdchest", 100}, --puestos hasta aquí
        {"Cajonera 1", "v_corp_filecabdark01", 100},
        {"Cajonera 2", "v_corp_filecabdark02", 100},
        {"Cajonera 3", "v_corp_filecabdark03", 100},
        {"Cajonera 4", "v_corp_filecablow", 100},
        {"Cajonera 5", "v_corp_filecabtall", 100},
        {"Cajonera 6", "v_corp_filecabtall_01", 100},
        {"Cajonera elegante","v_res_mdbedtable" , 75},
        {"Mueble de pared", "v_res_msoncabinet", 500},
        {"Mueble de pared", "v_corp_cabshelves01", 500},
        {"Estantería Grow", "prop_disp_cabinet_01", 400},
        {"Armario Motero", "bkr_prop_biker_garage_locker_01", 200},
        {"Taquilla 1", "p_cs_locker_01_s", 100},
        {"Estantería madera", "v_ret_ml_shelfrk", 90},
        {"Estantería metal", "prop_ff_shelves_01", 90},


    },
    ['accessory'] = {
        {'Reloj negro', 'p_watch_02_s', 75}, 
        {'Reloj blanco', 'p_watch_01_s', 75},
        {'Paquete de cigarros blanco', 'p_cigar_pack_02_s', 75},
        {'Paquete de cigarros rojo', 'p_fag_packet_01_s', 75},
        {'Cartera naranja', 'prop_ld_wallet_01_s', 75},
        {'Bolso marrón', 'prop_ld_handbag_s', 75},
        {'Mochila azul ', 'prop_m_pack_int_01', 75},
        {'Mochila de mano gris', 'prop_cs_heist_bag_02', 75},
        {'Bolsa de nigel', 'prop_nigel_bag_pickup', 75},
        {'Maleta negra', 'prop_ld_suitcase_01', 75}
    },
    ['ilegal'] = {
        {'Mesa drogas', 'v_med_benchcentr', 100000, "drugs"},
        {'Mesa crafteo', 'gr_prop_gr_bench_01b', 150000, "craft"},
    },
}