VEHICLE_TYPES = {
    CITY = {
        { model = 'asbo', price = 3800, data = {}, entity = nil, spawned = false },
        { model = 'blista', price = 4500, data = {}, entity = nil, spawned = false },
        { model = 'brioso2', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'club', price = 3600, data = {}, entity = nil, spawned = false },
        { model = 'clubgtr', price = 12000, data = {}, entity = nil, spawned = false },
        { model = 'cheburek', price = 3200, data = {}, entity = nil, spawned = false },
        { model = 'dilettante', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'fagaloa', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'issi2', price = 5000, data = {}, entity = nil, spawned = false },
        { model = 'panto', price = 3500, data = {}, entity = nil, spawned = false },
        { model = 'prairie', price = 4200, data = {}, entity = nil, spawned = false },
        { model = 'weevil', price = 4500, data = {}, entity = nil, spawned = false },
        { model = 'asea', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'asterope', price = 4600, data = {}, entity = nil, spawned = false },
        { model = 'emperor', price = 3000, data = {}, entity = nil, spawned = false },
        { model = 'glendale', price = 3400, data = {}, entity = nil, spawned = false },
        { model = 'ingot', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'premier', price = 3500, data = {}, entity = nil, spawned = false },
        { model = 'primo', price = 3500, data = {}, entity = nil, spawned = false },
        { model = 'regina', price = 2900, data = {}, entity = nil, spawned = false },
    },
    VILLAGE = {
        { model = 'astron', price = 127000, data = {}, entity = nil, spawned = false },
        { model = 'baller', price = 27000, data = {}, entity = nil, spawned = false },
        { model = 'baller2', price = 40000, data = {}, entity = nil, spawned = false },
        { model = 'baller3', price = 63000, data = {}, entity = nil, spawned = false },
        { model = 'baller4', price = 83000, data = {}, entity = nil, spawned = false },
        { model = 'bjxl', price = 22000, data = {}, entity = nil, spawned = false },
        { model = 'cavalcade', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'cavalcade2', price = 28000, data = {}, entity = nil, spawned = false },
        { model = 'contender', price = 34000, data = {}, entity = nil, spawned = false },
        { model = 'dubsta', price = 35000, data = {}, entity = nil, spawned = false },
        { model = 'dubsta2', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'habanero', price = 18000, data = {}, entity = nil, spawned = false },
        { model = 'huntley', price = 34000, data = {}, entity = nil, spawned = false },
        { model = 'iwagen', price = 110000, data = {}, entity = nil, spawned = false },
        { model = 'jubilee', price = 100000, data = {}, entity = nil, spawned = false },
        { model = 'landstalker', price = 19000, data = {}, entity = nil, spawned = false },
        { model = 'landstalker2', price = 43500, data = {}, entity = nil, spawned = false },
        { model = 'mesa', price = 23000, data = {}, entity = nil, spawned = false },
        { model = 'toros', price = 186000, data = {}, entity = nil, spawned = false },
    },
    JDM = {
        { model = 'blista2', price = 17500, data = {}, entity = nil, spawned = false },
        { model = 'calico', price = 43000, data = {}, entity = nil, spawned = false },
        { model = 'elegy', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'elegyrh7', price = 113000, data = {}, entity = nil, spawned = false },
        { model = 'euros', price = 57000, data = {}, entity = nil, spawned = false },
        { model = 'futo', price = 21000, data = {}, entity = nil, spawned = false },
        { model = 'futo2', price = 34000, data = {}, entity = nil, spawned = false },
        { model = 'jester3', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'jester4', price = 95000, data = {}, entity = nil, spawned = false },
        { model = 'kuruma', price = 63000, data = {}, entity = nil, spawned = false },
        { model = 'kawaii', price = 12000, data = {}, entity = nil, spawned = false },
        { model = 'previon', price = 15000, data = {}, entity = nil, spawned = false },
        { model = 'penumbra', price = 24000, data = {}, entity = nil, spawned = false },
        { model = 'penumbra2', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'remus', price = 36000, data = {}, entity = nil, spawned = false },
        { model = 'rt3000', price = 44000, data = {}, entity = nil, spawned = false },
        { model = 's230', price = 29500, data = {}, entity = nil, spawned = false },
        { model = 'sigma3', price = 18000, data = {}, entity = nil, spawned = false },
        { model = 'sugoi', price = 46000, data = {}, entity = nil, spawned = false },
        { model = 'sultan', price = 48000, data = {}, entity = nil, spawned = false },
        { model = 'sultan2', price = 51000, data = {}, entity = nil, spawned = false },
        { model = 'sultan3', price = 87000, data = {}, entity = nil, spawned = false },
        { model = 'warrener', price = 17300, data = {}, entity = nil, spawned = false },
        { model = 'z190', price = 33000, data = {}, entity = nil, spawned = false },
        { model = 'zr350', price = 78000, data = {}, entity = nil, spawned = false },
        { model = 'blade', price = 19500, data = {}, entity = nil, spawned = false },
        { model = 'buccaneer', price = 20000, data = {}, entity = nil, spawned = false },
        { model = 'buccaneer2', price = 23000, data = {}, entity = nil, spawned = false },
        { model = 'buffalo', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'buffalo2', price = 61000, data = {}, entity = nil, spawned = false },
        { model = 'chino', price = 16000, data = {}, entity = nil, spawned = false },
        { model = 'chino2', price = 19500, data = {}, entity = nil, spawned = false },
        { model = 'clique', price = 30000, data = {}, entity = nil, spawned = false },
        { model = 'coquette3', price = 47000, data = {}, entity = nil, spawned = false },
        { model = 'deviant', price = 54000, data = {}, entity = nil, spawned = false },
        { model = 'dominator', price = 35000, data = {}, entity = nil, spawned = false },
        { model = 'dominator3', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'dominator7', price = 54000, data = {}, entity = nil, spawned = false },
        --{ model = 'domc', price = 65000, data = {}, entity = nil, spawned = false },
        { model = 'dukes', price = 17500, data = {}, entity = nil, spawned = false },
        { model = 'ellie', price = 79000, data = {}, entity = nil, spawned = false },
        { model = 'faction', price = 15500, data = {}, entity = nil, spawned = false },
        { model = 'faction2', price = 20500, data = {}, entity = nil, spawned = false },
        { model = 'gauntlet', price = 34000, data = {}, entity = nil, spawned = false },
        { model = 'gauntlet3', price = 44000, data = {}, entity = nil, spawned = false },
        { model = 'gauntlet5', price = 48000, data = {}, entity = nil, spawned = false },
        { model = 'gauntlet4', price = 70000, data = {}, entity = nil, spawned = false },
        { model = 'hermes', price = 33000, data = {}, entity = nil, spawned = false },
        { model = 'hotknife', price = 41000, data = {}, entity = nil, spawned = false },
        { model = 'hustler', price = 38000, data = {}, entity = nil, spawned = false },
        { model = 'impaler', price = 44000, data = {}, entity = nil, spawned = false },
        { model = 'manana', price = 19000, data = {}, entity = nil, spawned = false },
        { model = 'manana2', price = 21000, data = {}, entity = nil, spawned = false },
        { model = 'nightshade', price = 42000, data = {}, entity = nil, spawned = false },
        { model = 'phoenix', price = 33000, data = {}, entity = nil, spawned = false },
        { model = 'picador', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'ratloader2', price = 36000, data = {}, entity = nil, spawned = false },
        { model = 'ruiner', price = 18000, data = {}, entity = nil, spawned = false },
        { model = 'sabregt', price = 27000, data = {}, entity = nil, spawned = false },
        { model = 'sabregt2', price = 32000, data = {}, entity = nil, spawned = false },
        { model = 'slamvan', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'slamvan2', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'slamvan3', price = 33000, data = {}, entity = nil, spawned = false },
        { model = 'stalion', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'tampa', price = 31000, data = {}, entity = nil, spawned = false },
        { model = 'tornado', price = 23000, data = {}, entity = nil, spawned = false },
        { model = 'tornado2', price = 27000, data = {}, entity = nil, spawned = false },
        { model = 'tornado5', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'tulip', price = 27000, data = {}, entity = nil, spawned = false },
        { model = 'vamos', price = 31000, data = {}, entity = nil, spawned = false },
        { model = 'velox', price = 36000, data = {}, entity = nil, spawned = false },
        { model = 'vigero', price = 19000, data = {}, entity = nil, spawned = false },
        { model = 'virgo', price = 16000, data = {}, entity = nil, spawned = false },
        { model = 'virgo2', price = 16000, data = {}, entity = nil, spawned = false },
        { model = 'voodoo', price = 31000, data = {}, entity = nil, spawned = false },
        { model = 'yosemite', price = 24000, data = {}, entity = nil, spawned = false },
    },
    MOTORCYCLES = {
        { model = 'akuma', price = 19000, data = {}, entity = nil, spawned = false },
        { model = 'avarus', price = 18500, data = {}, entity = nil, spawned = false },
        { model = 'bagger', price = 14500, data = {}, entity = nil, spawned = false },
        { model = 'bati', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'bf400', price = 21000, data = {}, entity = nil, spawned = false },
        { model = 'blazer', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'carbonrs', price = 30000, data = {}, entity = nil, spawned = false },
        { model = 'chimera', price = 28000, data = {}, entity = nil, spawned = false },
        { model = 'cliffhanger', price = 14000, data = {}, entity = nil, spawned = false },
        { model = 'daemon2', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'defiler', price = 17500, data = {}, entity = nil, spawned = false },
        { model = 'diablous', price = 23000, data = {}, entity = nil, spawned = false },
        { model = 'diablous2', price = 32000, data = {}, entity = nil, spawned = false },
        { model = 'double', price = 24000, data = {}, entity = nil, spawned = false },
        { model = 'enduro', price = 14000, data = {}, entity = nil, spawned = false },
        { model = 'esskey', price = 11000, data = {}, entity = nil, spawned = false },
        { model = 'faggio', price = 3500, data = {}, entity = nil, spawned = false },
        { model = 'faggio2', price = 3600, data = {}, entity = nil, spawned = false },
        { model = 'faggio3', price = 3800, data = {}, entity = nil, spawned = false },
        { model = 'fcr', price = 11500, data = {}, entity = nil, spawned = false },
        { model = 'fcr2', price = 13500, data = {}, entity = nil, spawned = false },
        { model = 'gargoyle', price = 14500, data = {}, entity = nil, spawned = false },
        { model = 'hakuchou', price = 38000, data = {}, entity = nil, spawned = false },
        { model = 'hexer', price = 18500, data = {}, entity = nil, spawned = false },
        { model = 'innovation', price = 23500, data = {}, entity = nil, spawned = false },
        { model = 'lectro', price = 13500, data = {}, entity = nil, spawned = false },
        { model = 'manchez', price = 11500, data = {}, entity = nil, spawned = false },
        { model = 'nemesis', price = 13500, data = {}, entity = nil, spawned = false },
        { model = 'nightblade', price = 28500, data = {}, entity = nil, spawned = false },
        { model = 'pcj', price = 10500, data = {}, entity = nil, spawned = false },
        { model = 'reever', price = 32500, data = {}, entity = nil, spawned = false },
        { model = 'ruffian', price = 16500, data = {}, entity = nil, spawned = false },
        { model = 'sanchez', price = 12500, data = {}, entity = nil, spawned = false },
        { model = 'sanchez2', price = 12500, data = {}, entity = nil, spawned = false },
        { model = 'sanctus', price = 37500, data = {}, entity = nil, spawned = false },
        { model = 'shinobi', price = 42500, data = {}, entity = nil, spawned = false },
        { model = 'sovereign', price = 23500, data = {}, entity = nil, spawned = false },
        { model = 'stryder', price = 20500, data = {}, entity = nil, spawned = false },
        { model = 'thrust', price = 15500, data = {}, entity = nil, spawned = false },
        { model = 'vader', price = 10500, data = {}, entity = nil, spawned = false },
        { model = 'verus', price = 21000, data = {}, entity = nil, spawned = false },
        { model = 'vortex', price = 25500, data = {}, entity = nil, spawned = false },
        { model = 'wolfsbane', price = 17500, data = {}, entity = nil, spawned = false },
        { model = 'zombiea', price = 19500, data = {}, entity = nil, spawned = false },
        { model = 'zombieb', price = 19500, data = {}, entity = nil, spawned = false },
        { model = 'bmx', price = 300, data = {}, entity = nil, spawned = false },
        { model = 'tribike', price = 500, data = {}, entity = nil, spawned = false },
        { model = 'cruiser', price = 300, data = {}, entity = nil, spawned = false },
        { model = 'scorcher', price = 500, data = {}, entity = nil, spawned = false },
        { model = 'africat', price = 47000, data = {}, entity = nil, spawned = false },
    },
    SANDY = {
        { model = 'bifta', price = 13000, data = {}, entity = nil, spawned = false },
        { model = 'brawler', price = 97000, data = {}, entity = nil, spawned = false },
        { model = 'caracara2', price = 75000, data = {}, entity = nil, spawned = false },
        { model = 'dubsta3', price = 280000, data = {}, entity = nil, spawned = false },
        { model = 'dune', price = 11000, data = {}, entity = nil, spawned = false },
        { model = 'everon', price = 46000, data = {}, entity = nil, spawned = false },
        { model = 'guardian', price = 175000, data = {}, entity = nil, spawned = false },
        { model = 'hellion', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'kalahari', price = 4000, data = {}, entity = nil, spawned = false },
        { model = 'kamacho', price = 174000, data = {}, entity = nil, spawned = false },
        { model = 'mesa3', price = 57000, data = {}, entity = nil, spawned = false },
        { model = 'mesar', price = 77000, data = {}, entity = nil, spawned = false },
        { model = 'outlaw', price = 65000, data = {}, entity = nil, spawned = false },
        { model = 'rancherxl', price = 12000, data = {}, entity = nil, spawned = false },
        { model = 'rebel2', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'riata', price = 29000, data = {}, entity = nil, spawned = false },
        { model = 'sandking', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'sandking2', price = 48000, data = {}, entity = nil, spawned = false },
        { model = 'yosemite3', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'bison', price = 28000, data = {}, entity = nil, spawned = false },
        { model = 'bobcatxl', price = 18000, data = {}, entity = nil, spawned = false },
        { model = 'burrito3', price = 13500, data = {}, entity = nil, spawned = false },
        { model = 'minivan', price = 14000, data = {}, entity = nil, spawned = false },
        { model = 'moonbeam', price = 31000, data = {}, entity = nil, spawned = false },
        { model = 'rumpo3', price = 27000, data = {}, entity = nil, spawned = false },
        { model = 'speedo', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'surfer', price = 19000, data = {}, entity = nil, spawned = false },
        { model = 'youga', price = 19500, data = {}, entity = nil, spawned = false },
        { model = 'youga2', price = 24500, data = {}, entity = nil, spawned = false },
        { model = 'youga3', price = 28500, data = {}, entity = nil, spawned = false },
    },
    CITY2 = {
        { model = 'cog55', price = 47000, data = {}, entity = nil, spawned = false },
        { model = 'cognoscenti', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'fugitive', price = 17000, data = {}, entity = nil, spawned = false },
        { model = 'glendale2', price = 9300, data = {}, entity = nil, spawned = false },
        { model = 'intruder', price = 16500, data = {}, entity = nil, spawned = false },
        { model = 'primo2', price = 11300, data = {}, entity = nil, spawned = false },
        { model = 'schafter2', price = 41000, data = {}, entity = nil, spawned = false },
        { model = 'schafter3', price = 47000, data = {}, entity = nil, spawned = false },
        { model = 'schafter4', price = 56000, data = {}, entity = nil, spawned = false },
        { model = 'stafford', price = 55000, data = {}, entity = nil, spawned = false },
        { model = 'stanier', price = 8700, data = {}, entity = nil, spawned = false },
        { model = 'stratum', price = 15300, data = {}, entity = nil, spawned = false },
        { model = 'superd', price = 76000, data = {}, entity = nil, spawned = false },
        { model = 'surge', price = 21300, data = {}, entity = nil, spawned = false },
        { model = 'tailgater', price = 33600, data = {}, entity = nil, spawned = false },
        { model = 'washington', price = 11300, data = {}, entity = nil, spawned = false },
        { model = 'cinquemila', price = 107000, data = {}, entity = nil, spawned = false },
        { model = 'cogcabrio', price = 85000, data = {}, entity = nil, spawned = false },
        { model = 'cypher', price = 78000, data = {}, entity = nil, spawned = false },
        { model = 'deity', price = 124000, data = {}, entity = nil, spawned = false },
        { model = 'exemplar', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'f620', price = 78000, data = {}, entity = nil, spawned = false },
        { model = 'felon', price = 45000, data = {}, entity = nil, spawned = false },
        { model = 'felon2', price = 49000, data = {}, entity = nil, spawned = false },
        { model = 'jackal', price = 47000, data = {}, entity = nil, spawned = false },
        { model = 'michelli', price = 45000, data = {}, entity = nil, spawned = false },
        { model = 'nebula', price = 15000, data = {}, entity = nil, spawned = false },
        { model = 'peyote', price = 12000, data = {}, entity = nil, spawned = false },
        { model = 'peyote3', price = 13000, data = {}, entity = nil, spawned = false },
        { model = 'pigalle', price = 55000, data = {}, entity = nil, spawned = false },
        { model = 'schwarzer', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'sentinel', price = 41000, data = {}, entity = nil, spawned = false },
        { model = 'sentinel2', price = 43000, data = {}, entity = nil, spawned = false },
        { model = 'vectre', price = 79000, data = {}, entity = nil, spawned = false },
        { model = 'windsor', price = 72000, data = {}, entity = nil, spawned = false },
        { model = 'windsor2', price = 75000, data = {}, entity = nil, spawned = false },
        { model = 'zion', price = 39000, data = {}, entity = nil, spawned = false },
        { model = 'zion2', price = 44000, data = {}, entity = nil, spawned = false },
        { model = 'alpha', price = 38000, data = {}, entity = nil, spawned = false },
        { model = 'banshee', price = 86000, data = {}, entity = nil, spawned = false },
        { model = 'bestiagts', price = 92000, data = {}, entity = nil, spawned = false },
        { model = 'brioso', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'carbonizzare', price = 78000, data = {}, entity = nil, spawned = false },
        { model = 'comet2', price = 58000, data = {}, entity = nil, spawned = false },
        { model = 'comet5', price = 67000, data = {}, entity = nil, spawned = false },
        { model = 'comet6', price = 80000, data = {}, entity = nil, spawned = false },
        { model = 'coquette', price = 56000, data = {}, entity = nil, spawned = false },
        { model = 'coquette4', price = 87000, data = {}, entity = nil, spawned = false },
        { model = 'drafter', price = 55000, data = {}, entity = nil, spawned = false },
        { model = 'elegy2', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'feltzer2', price = 46000, data = {}, entity = nil, spawned = false },
        { model = 'flashgt', price = 76000, data = {}, entity = nil, spawned = false },
        { model = 'furoregt', price = 63000, data = {}, entity = nil, spawned = false },
        { model = 'fusilade', price = 31000, data = {}, entity = nil, spawned = false },
        { model = 'gb200', price = 64000, data = {}, entity = nil, spawned = false },
        { model = 'growler', price = 110000, data = {}, entity = nil, spawned = false },
        { model = 'imorgon', price = 87000, data = {}, entity = nil, spawned = false },
        { model = 'italigto', price = 112000, data = {}, entity = nil, spawned = false },
        { model = 'jugular', price = 75000, data = {}, entity = nil, spawned = false },
        { model = 'jester', price = 135000, data = {}, entity = nil, spawned = false },
        { model = 'khamelion', price = 84000, data = {}, entity = nil, spawned = false },
        { model = 'komoda', price = 75000, data = {}, entity = nil, spawned = false },
        { model = 'locust', price = 101000, data = {}, entity = nil, spawned = false },
        { model = 'lynx', price = 77000, data = {}, entity = nil, spawned = false },
        { model = 'masacro', price = 72000, data = {}, entity = nil, spawned = false },
        { model = 'neo', price = 146000, data = {}, entity = nil, spawned = false },
        { model = 'neon', price = 166000, data = {}, entity = nil, spawned = false },
        { model = 'ninef', price = 112000, data = {}, entity = nil, spawned = false },
        { model = 'ninef2', price = 121000, data = {}, entity = nil, spawned = false },
        { model = 'paragon', price = 91000, data = {}, entity = nil, spawned = false },
        { model = 'pariah', price = 130000, data = {}, entity = nil, spawned = false },
        { model = 'raiden', price = 76000, data = {}, entity = nil, spawned = false },
        { model = 'issi7', price = 68000, data = {}, entity = nil, spawned = false },
        { model = 'rapidgt', price = 69000, data = {}, entity = nil, spawned = false },
        { model = 'rapidgt2', price = 73000, data = {}, entity = nil, spawned = false },
        { model = 'ruston', price = 81000, data = {}, entity = nil, spawned = false },
        { model = 'schlagen', price = 104000, data = {}, entity = nil, spawned = false },
        { model = 'seven70', price = 178000, data = {}, entity = nil, spawned = false },
        { model = 'specter', price = 126000, data = {}, entity = nil, spawned = false },
        { model = 'surano', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'verlierer2', price = 76000, data = {}, entity = nil, spawned = false },
        { model = 'vstr', price = 61000, data = {}, entity = nil, spawned = false },
        { model = 'tailgater2', price = 78000, data = {}, entity = nil, spawned = false },
    },
    VIP = {
        { model = 'adder', price = 281000, data = {}, entity = nil, spawned = false },
        { model = 'autarch', price = 227000, data = {}, entity = nil, spawned = false },
        { model = 'banshee', price = 124000, data = {}, entity = nil, spawned = false },
        { model = 'bullet', price = 114000, data = {}, entity = nil, spawned = false },
        { model = 'cheetah', price = 205000, data = {}, entity = nil, spawned = false },
        { model = 'cyclone', price = 196000, data = {}, entity = nil, spawned = false },
        { model = 'entity2', price = 317000, data = {}, entity = nil, spawned = false },
        { model = 'entityxf', price = 325000, data = {}, entity = nil, spawned = false },
        { model = 'emerus', price = 213000, data = {}, entity = nil, spawned = false },
        { model = 'fmj', price = 245000, data = {}, entity = nil, spawned = false },
        { model = 'furia', price = 146000, data = {}, entity = nil, spawned = false },
        { model = 'gp1', price = 306000, data = {}, entity = nil, spawned = false },
        { model = 'ignus', price = 347000, data = {}, entity = nil, spawned = false },
        { model = 'infernus', price = 147000, data = {}, entity = nil, spawned = false },
        { model = 'italigtb', price = 217000, data = {}, entity = nil, spawned = false },
        { model = 'italigtb2', price = 227000, data = {}, entity = nil, spawned = false },
        { model = 'italirsx', price = 335000, data = {}, entity = nil, spawned = false },
        { model = 'krieger', price = 321000, data = {}, entity = nil, spawned = false },
        { model = 'nero', price = 357000, data = {}, entity = nil, spawned = false },
        { model = 'rsvr16', price = 283000, data = {}, entity = nil, spawned = false },
        { model = 'nero2', price = 379000, data = {}, entity = nil, spawned = false },
        { model = 'pts21', price = 532000, data = {}, entity = nil, spawned = false },
        { model = 'ursa', price = 248000, data = {}, entity = nil, spawned = false },
        { model = 'yzfr125', price = 74000, data = {}, entity = nil, spawned = false },
        { model = '12charger', price = 185500, data = {}, entity = nil, spawned = false },
        { model = 'osiris', price = 285000, data = {}, entity = nil, spawned = false },
        { model = 'penetrator', price = 207000, data = {}, entity = nil, spawned = false },
        { model = 'pfister811', price = 197000, data = {}, entity = nil, spawned = false },
        { model = 'reaper', price = 149000, data = {}, entity = nil, spawned = false },
        { model = 'sc1', price = 218000, data = {}, entity = nil, spawned = false },
        { model = 't20', price = 233000, data = {}, entity = nil, spawned = false },
        { model = 'taipan', price = 283000, data = {}, entity = nil, spawned = false },
        { model = 'tempesta', price = 189000, data = {}, entity = nil, spawned = false },
        { model = 'thrax', price = 397000, data = {}, entity = nil, spawned = false },
        { model = 'turismor', price = 187000, data = {}, entity = nil, spawned = false },
        { model = 'tyrant', price = 291000, data = {}, entity = nil, spawned = false },
        { model = 'vacca', price = 156000, data = {}, entity = nil, spawned = false },
        { model = 'voltic', price = 109000, data = {}, entity = nil, spawned = false },
        { model = 'xa21', price = 277000, data = {}, entity = nil, spawned = false },
        { model = 'zeno', price = 313000, data = {}, entity = nil, spawned = false },
        { model = 'zentorno', price = 233000, data = {}, entity = nil, spawned = false },
        { model = 'zorruso', price = 310000, data = {}, entity = nil, spawned = false },
        { model = 'btype', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'btype3', price = 87000, data = {}, entity = nil, spawned = false },
        { model = 'casco', price = 65000, data = {}, entity = nil, spawned = false },
        { model = 'cheetah2', price = 128000, data = {}, entity = nil, spawned = false },
        { model = 'coquette2', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'comet3', price = 65000, data = {}, entity = nil, spawned = false },
        { model = 'dynasty', price = 21000, data = {}, entity = nil, spawned = false },
        { model = 'feltzer3', price = 266000, data = {}, entity = nil, spawned = false },
        { model = 'gt500', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'infernus2', price = 146000, data = {}, entity = nil, spawned = false },
        { model = 'mamba', price = 76000, data = {}, entity = nil, spawned = false },
        { model = 'monroe', price = 117000, data = {}, entity = nil, spawned = false },
        { model = 'rapidgt3', price = 44000, data = {}, entity = nil, spawned = false },
        { model = 'retinue2', price = 66000, data = {}, entity = nil, spawned = false },
        { model = 'sentinel3', price = 50000, data = {}, entity = nil, spawned = false },
        { model = 'stinger', price = 78000, data = {}, entity = nil, spawned = false },
        { model = 'stingergt', price = 96000, data = {}, entity = nil, spawned = false },
        { model = 'swinger', price = 224000, data = {}, entity = nil, spawned = false },
        { model = 'torero', price = 151000, data = {}, entity = nil, spawned = false },
        { model = 'tropos', price = 86000, data = {}, entity = nil, spawned = false },
        { model = 'turismo2', price = 129000, data = {}, entity = nil, spawned = false },
        { model = 'viseris', price = 97000, data = {}, entity = nil, spawned = false },
        { model = 'ztype', price = 327000, data = {}, entity = nil, spawned = false },
        { model = 'zion3', price = 57000, data = {}, entity = nil, spawned = false },
    },
   -- DRIFT = {
        --{ model = '180sx', price = 50, data = {}, entity = nil, spawned = false },
        --{ model = 'GODzTCPMRX7FD', price = 50, data = {}, entity = nil, spawned = false },
        --{ model = 'is300', price = 50, data = {}, entity = nil, spawned = false },
        --{ model = 'majsr', price = 50, data = {}, entity = nil, spawned = false },
        --{ model = 's14', price = 50, data = {}, entity = nil, spawned = false },
    --},
    BOATS = {
        { model = 'seashark', price = 10000, data = {}, entity = nil, spawned = false },
        { model = 'squalo', price = 25000, data = {}, entity = nil, spawned = false },
        { model = 'suntrap', price = 22000, data = {}, entity = nil, spawned = false },
        { model = 'tropic', price = 20000, data = {}, entity = nil, spawned = false },
        { model = 'dinghy', price = 15000, data = {}, entity = nil, spawned = false },
        --{ model = 'marquis', price = 35000, data = {}, entity = nil, spawned = false },
    },
    --BV = {
        --{ model = 'speeder', price = 10, data = {}, entity = nil, spawned = false },
        --{ model = 'toro', price = 10, data = {}, entity = nil, spawned = false },
        --{ model = 'longfin', price = 10, data = {}, entity = nil, spawned = false },
    --},
    -- AIRPLANE = {
    --     { model = 'dodo', price = 3000000, data = {}, entity = nil, spawned = false },
    --     { model = 'microlight', price = 1000000, data = {}, entity = nil, spawned = false },
    --     { model = 'besra', price = 8000000, data = {}, entity = nil, spawned = false },
    -- },
    -- AIRVIP = {
    --     --{ model = 'gulfiv', price = 75, data = {}, entity = nil, spawned = false },
    --     --{ model = 'b1900', price = 75, data = {}, entity = nil, spawned = false },
    --     --{ model = 's340', price = 60, data = {}, entity = nil, spawned = false },
    -- },
    -- HELICOPTERS = {
    --     { model = 'conada', price = 4500000, data = {}, entity = nil, spawned = false },
    --     { model = 'havok', price = 1000000, data = {}, entity = nil, spawned = false },
    --     --{ model = 'seasparrow3', price = 2000000, data = {}, entity = nil, spawned = false },
    --     { model = 'seasparrow2', price = 1750000, data = {}, entity = nil, spawned = false },
    --     { model = 'seasparrow', price = 1500000, data = {}, entity = nil, spawned = false },
    -- },
    -- HELIVIP = {
    --     { model = 'volatus', price = 55, data = {}, entity = nil, spawned = false },
    --     { model = 'supervolito2', price = 45, data = {}, entity = nil, spawned = false },
    --     { model = 'supervolito', price = 45, data = {}, entity = nil, spawned = false },
    --     { model = 'swift2', price = 55, data = {}, entity = nil, spawned = false },
    --     { model = 'frogger', price = 35, data = {}, entity = nil, spawned = false },
    -- }
}

VEHICLE_SPOTS = { 
    CITY = {
        { x = -49.85, y = -1083.49, z = 26.0, w = 157.22, spot = 1, vehicleShop = 'CITY', data = {} },
        { x = -36.84, y = -1093.32, z = 26.0, w = 107.37, spot = 2, vehicleShop = 'CITY', data = {} },
        { x = -47.82, y = -1092.04, z = 26.0, w = 193.21, spot = 3, vehicleShop = 'CITY', data = {} },
        { x = -54.34, y = -1096.62, z = 26.0, w = 298.87, spot = 4, vehicleShop = 'CITY', data = {} },
        { x = -42.22, y = -1101.67, z = 26.0, w = 287.83, spot = 5, vehicleShop = 'CITY', data = {} },
    },
    JDM = {
        { x = 1133.69, y = -3139.0, z = 4.9, w = 358.6, spot = 1, vehicleShop = 'JDM', data = {} },
        { x = 1128.31, y = -3139.0, z = 4.9, w = 358.6, spot = 2, vehicleShop = 'JDM', data = {} },
        { x = 1122.87, y = -3139.0, z = 4.9, w = 358.6, spot = 3, vehicleShop = 'JDM', data = {} },
        { x = 1117.61, y = -3139.0, z = 4.9, w = 358.6, spot = 4, vehicleShop = 'JDM', data = {} },
        { x = 1112.26, y = -3139.0, z = 4.9, w = 358.6, spot = 5, vehicleShop = 'JDM', data = {} },
        { x = 1106.79, y = -3139.0, z = 4.9, w = 358.6, spot = 6, vehicleShop = 'JDM', data = {} },
        { x = 1101.41, y = -3139.0, z = 4.9, w = 358.6, spot = 7, vehicleShop = 'JDM', data = {} },
    },
    CITY2 = {
        { x = -604.32, y = -2219.84, z = 4.61, w = 179.92, spot = 1, vehicleShop = 'CITY2', data = {} },
        { x = -609.4, y = -2216.24, z = 4.61, w = 179.56, spot = 2, vehicleShop = 'CITY2', data = {} },
        { x = -614.0, y = -2212.32, z = 4.61, w = 184.4, spot = 3, vehicleShop = 'CITY2', data = {} },
        { x = -618.92, y = -2207.92, z = 4.61, w = 180.36, spot = 4, vehicleShop = 'CITY2', data = {} },
        { x = -623.76, y = -2203.84, z = 4.61, w = 180.16, spot = 5, vehicleShop = 'CITY2', data = {} },
        { x = -628.52, y = -2199.52, z = 4.61, w = 182.88, spot = 6, vehicleShop = 'CITY2', data = {} },
        { x = -633.56, y = -2195.44, z = 4.61, w = 181.36, spot = 7, vehicleShop = 'CITY2', data = {} },
        { x = -638.4, y = -2191.52, z = 4.61, w = 182.96, spot = 8, vehicleShop = 'CITY2', data = {} },
        { x = -643.32, y = -2187.92, z = 4.61, w = 181.28, spot = 9, vehicleShop = 'CITY2', data = {} },
        { x = -647.92, y = -2183.68, z = 4.61, w = 181.56, spot = 10, vehicleShop = 'CITY2', data = {} },
        { x = -600.24, y = -2215.2, z = 4.61, w = 5.32, spot = 11, vehicleShop = 'CITY2', data = {} },
        { x = -605.08, y = -2211.28, z = 4.61, w = 2.36, spot = 12, vehicleShop = 'CITY2', data = {} },
        { x = -609.92, y = -2206.84, z = 4.61, w = 0.92, spot = 13, vehicleShop = 'CITY2', data = {} },
        { x = -614.64, y = -2202.64, z = 4.61, w = 2.68, spot = 14, vehicleShop = 'CITY2', data = {} },
        { x = -619.68, y = -2198.64, z = 4.61, w = 1.16, spot = 15, vehicleShop = 'CITY2', data = {} },
        { x = -624.52, y = -2194.44, z = 4.61, w = 2.08, spot = 16, vehicleShop = 'CITY2', data = {} },
        { x = -629.36, y = -2190.68, z = 4.61, w = 3.04, spot = 17, vehicleShop = 'CITY2', data = {} },
        { x = -634.24, y = -2186.4, z = 4.61, w = 3.68, spot = 18, vehicleShop = 'CITY2', data = {} },
        { x = -639.16, y = -2182.32, z = 4.61, w = 2.04, spot = 19, vehicleShop = 'CITY2', data = {} },
        { x = -643.96, y = -2178.36, z = 4.61, w = 0.8, spot = 20, vehicleShop = 'CITY2', data = {} },
        { x = -648.92, y = -2174.32, z = 4.61, w = 5.4, spot = 21, vehicleShop = 'CITY2', data = {} },
    },
    VILLAGE = {
        -- { x = -42.8, y = 6475.9, z = 31.08, w = 348.31, spot = 1, vehicleShop = 'VILLAGE', data = {} },
        { x = 37.42, y = 6483.78, z = 31.03, w = 272.89, spot = 1, vehicleShop = 'VILLAGE', data = {} },
        { x = 46.82, y = 6473.27, z = 31.05, w = 6.81, spot = 2, vehicleShop = 'VILLAGE', data = {} },
        { x = 53.5, y = 6474.86, z = 31.03, w = 44.84, spot = 3, vehicleShop = 'VILLAGE', data = {} },
        { x = 55.76, y = 6477.43, z = 31.03, w = 44.75, spot = 4, vehicleShop = 'VILLAGE', data = {} },
        { x = 43.16, y = 6475.87, z = 31.06, w = 356.34, spot = 5, vehicleShop = 'VILLAGE', data = {} },
        { x = 47.47, y = 6481.68, z = 31.06, w = 248.96, spot = 5, vehicleShop = 'VILLAGE', data = {} },
    },
    MOTORCYCLES = {
        { x = 290.77, y = -1150.8, z = 28.82, w = 33.92, spot = 1, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 295.48, y = -1150.6, z = 28.82, w = 40.28, spot = 2, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 303.23, y = -1155.84, z = 28.82, w = 230.33, spot = 3, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 299.96, y = -1150.52, z = 28.33, w = 39.84, spot = 4, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 303.52, y = -1151.44, z = 28.33, w = 245.56, spot = 5, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 298.76, y = -1158.04, z = 28.33, w = 29.12, spot = 6, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 294.12, y = -1157.96, z = 28.33, w = 43.08, spot = 7, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 300.48, y = -1154.08, z = 28.33, w = 38.32, spot = 8, vehicleShop = 'MOTORCYCLES', data = {} },
        { x = 294.44, y = -1154.4, z = 28.33, w = 26.6, spot = 9, vehicleShop = 'MOTORCYCLES', data = {} },
    },
    SANDY = {
        { x = 1218.19, y = 2713.82, z = 37.58, w = 175.77, spot = 1, vehicleShop = 'SANDY', data = {} },
        { x = 1217.2, y = 2704.72, z = 37.58, w = 177.82, spot = 2, vehicleShop = 'SANDY', data = {} },
        { x = 1223.76, y = 2713.69, z = 37.58, w = 179.97, spot = 3, vehicleShop = 'SANDY', data = {} },
        { x = 1228.88, y = 2713.39, z = 37.58, w = 179.72, spot = 4, vehicleShop = 'SANDY', data = {} },
        { x = 1228.41, y = 2704.12, z = 37.58, w = 173.99, spot = 5, vehicleShop = 'SANDY', data = {} },
        { x = 1223.21, y = 2704.27, z = 37.58, w = 176.58, spot = 6, vehicleShop = 'SANDY', data = {} },
        { x = 1207.09, y = 2714.18, z = 37.58, w = 270.27, spot = 7, vehicleShop = 'SANDY', data = {} },
        { x = 1207.52, y = 2719.83, z = 37.58, w = 244.91, spot = 8, vehicleShop = 'SANDY', data = {} },
        { x = 1210.62, y = 2724.3, z = 37.58, w = 232.03, spot = 9, vehicleShop = 'SANDY', data = {} },
    },
    VIP = {
        { x = 422.09, y = 241.17, z = 102.78, w = 248.56, spot = 1, vehicleShop = 'VIP', data = {} },
        { x = 424.87, y = 249.18, z = 102.79, w = 249.18, spot = 2, vehicleShop = 'VIP', data = {} },
        { x = 427.41, y = 256.6, z = 102.8, w = 245.45, spot = 3, vehicleShop = 'VIP', data = {} },
        { x = 430.33, y = 264.24, z = 102.8, w = 247.79, spot = 4, vehicleShop = 'VIP', data = {} },
        { x = 433.31, y = 271.92, z = 102.8, w = 249.74, spot = 5, vehicleShop = 'VIP', data = {} },
    },
    -- DRIFT = {
    --     { x = 967.73, y = -1751.61, z = 20.3, w = 175.51, spot = 1, vehicleShop = 'DRIFT', data = {} },
    --     --{ x = 957.44, y = -1750.68, z = 20.3, w = 175.51, spot = 2, vehicleShop = 'DRIFT', data = {} },
    --     --{ x = 954.21, y = -1750.31, z = 20.3, w = 175.51, spot = 3, vehicleShop = 'DRIFT', data = {} },
    --     { x = 948.39, y = -1749.9, z = 20.3, w = 175.51, spot = 4, vehicleShop = 'DRIFT', data = {} },
    --     { x = 954.96, y = -1769.83, z = 20.3, w = 353.84, spot = 5, vehicleShop = 'DRIFT', data = {} },
    -- },
    BOATS = {
        { x = -731.81, y = -1334.32, z = -0.40, w = 228.35, spot = 1, vehicleShop = 'BOATS', data = {} },
        { x = -738.01, y = -1340.6, z = -0.40, w = 228.35, spot = 2, vehicleShop = 'BOATS', data = {} },
    },
    -- BV = {
    --     { x = -773.55, y = -1385.95, z = -0.80, w = 228.35, spot = 1, vehicleShop = 'BV', data = {} },
    -- },
    -- AIRPLANE = {
    --     { x = -1254.37, y = -3387.27, z = 15.80, w = 328.35, spot = 1, vehicleShop = 'AIRPLANE', data = {} },
    --     { x = -1270.19, y = -3378.04, z = 15.80, w = 328.35, spot = 2, vehicleShop = 'AIRPLANE', data = {} },
    --     { x = -1286.97, y = -3371.32, z = 15.80, w = 328.35, spot = 3, vehicleShop = 'AIRPLANE', data = {} },
    -- },
    -- AIRVIP = {
    --     { x = -994.56, y = -3016.1, z = 15.80, w = 61.42, spot = 1, vehicleShop = 'AIRVIP', data = {} },
    --     { x = -970.92, y = -2999.66, z = 15.80, w = 61.42, spot = 2, vehicleShop = 'AIRVIP', data = {} },
    --     { x = -970.55, y = -2970.26, z = 15.80, w = 61.42, spot = 3, vehicleShop = 'AIRVIP', data = {} },
    -- },
    -- HELICOPTERS = {
    --     { x = -1055.41, y = -2911.91, z = 14.80, w = 150.35, spot = 1, vehicleShop = 'HELICOPTERS', data = {} },
    --     { x = -1064.51, y = -2904.07, z = 14.80, w = 150.35, spot = 2, vehicleShop = 'HELICOPTERS', data = {} },
    --     { x = -1074.15, y = -2898.69, z = 14.80, w = 150.35, spot = 3, vehicleShop = 'HELICOPTERS', data = {} },
    -- },
    -- HELIVIP = {
    --     { x = -1635.48, y = -3150.04, z = 15.80, w = 327.05, spot = 1, vehicleShop = 'HELIVIP', data = {} },
    --     { x = -1658.05, y = -3153.27, z = 15.80, w = 327.05, spot = 2, vehicleShop = 'HELIVIP', data = {} },
    --     { x = -1665.2, y = -3128.67, z = 15.80, w = 327.05, spot = 3, vehicleShop = 'HELIVIP', data = {} },
    -- }
}

VEHICLE_DATA = {
    LIST = {
        CITY = VEHICLE_TYPES.CITY,
        CITY2 = VEHICLE_TYPES.CITY2,
        JDM = VEHICLE_TYPES.JDM,
        VILLAGE = VEHICLE_TYPES.VILLAGE,
        MOTORCYCLES = VEHICLE_TYPES.MOTORCYCLES,
        SANDY = VEHICLE_TYPES.SANDY,
        VIP = VEHICLE_TYPES.VIP,
        --DRIFT = VEHICLE_TYPES.DRIFT,
        BOATS = VEHICLE_TYPES.BOATS,
        --BV = VEHICLE_TYPES.BV
        --AIRPLANE = VEHICLE_TYPES.AIRPLANE,
        --AIRVIP = VEHICLE_TYPES.AIRVIP,
        --HELICOPTERS = VEHICLE_TYPES.HELICOPTERS,
        --HELIVIP = VEHICLE_TYPES.HELIVIP
    },
    SPOTS = {
        CITY = VEHICLE_SPOTS.CITY,
        JDM = VEHICLE_SPOTS.JDM,
        CITY2 = VEHICLE_SPOTS.CITY2,
        VILLAGE = VEHICLE_SPOTS.VILLAGE,
        MOTORCYCLES = VEHICLE_SPOTS.MOTORCYCLES,
        SANDY = VEHICLE_SPOTS.SANDY,
        VIP = VEHICLE_SPOTS.VIP,
        --DRIFT = VEHICLE_SPOTS.DRIFT,
        BOATS = VEHICLE_SPOTS.BOATS,
       -- BV = VEHICLE_SPOTS.BV
        --AIRPLANE = VEHICLE_SPOTS.AIRPLANE,
        --AIRVIP = VEHICLE_SPOTS.AIRVIP,
        --HELICOPTERS = VEHICLE_SPOTS.HELICOPTERS,
        --HELIVIP = VEHICLE_SPOTS.HELIVIP
    },
    GARAGES = {
        CITY = 'Garaje Central',
        JDM = 'Garaje Central',
        CITY2 = 'Garaje Central',
        MOTORCYCLES = 'Garaje Central',
        SANDY = 'Garaje Central',
        VIP = 'Garaje Central',
        VILLAGE = 'Garaje Central',
        --DRIFT = 'Garaje Central',
        BOATS = 'Puerto',
        --BV = 'Puerto',
        --AIRPLANE = 'Aeropuerto',
        --AIRVIP = 'Aeropuerto',
        --HELICOPTERS = 'Aeropuerto',
        --HELIVIP = 'Aeropuerto',
    },
    BUY = {
        CITY = vec3(-30.08, -1105.1, 26.42),
        JDM = vec3(-30.08, -1105.1, 26.42),
        CITY2 = vec3(-612.12, -2236.36, 6.17),
        MOTORCYCLES = vec3(278.08, -1152.44, 29.33),
        VILLAGE = vec3(-44.61, 6482.86, 31.44),
        SANDY = vec3(1228.64, 2733.48, 38.09),
        BOATS = vec3(-711.63, -1299.31, 5.4),
       -- BV = vec3(-711.63, -1299.31, 5.4),
        VIP = vec3(435.93, 215.35, 103.17),
       -- DRIFT = vec3(953.22, -1698.37, 128.3)
        --AIRPLANE = vec3(-1270.19, -3378.04, 14.80),
        --AIRVIP = vec3(-970.92, -2999.66, 14.80),
        --HELICOPTERS = vec3(-1064.51, -2904.07, 13.90),
        --HELIVIP = vec3(-1658.05, -3153.27, 13.90)
    },
    COPY = {
        CITY = vec3(-31.79, -1113.89, 26.42),
        JDM = vec3(-31.79, -1113.89, 26.42),
        CITY2 = vec3(-617.64, -2243.32, 6.21),
        MOTORCYCLES = vec3(275.12, -1152.36, 29.33),
        VILLAGE = vec3(-44.61, 6482.86, 31.44),
        SANDY = vec3(1224.76, 2728.0, 38.05),
        POLICE = vec3(468.6, -974.84, 27.33),
        BOATS = vec3(-698.7, -1283.9, 9.55),
       -- BV = vec3(-698.7, -1283.9, 9.55),
        VIP = vec3(433.45, 219.06, 103.16),
        --DRIFT = vec3(953.22, -1698.37, 128.3)
        --AIRPLANE = vec3(-1270.19, -3378.04, 14.80),
        --AIRVIP = vec3(-970.92, -2999.66, 14.80),
        --HELICOPTERS = vec3(-1064.51, -2904.07, 13.90),
        --HELIVIP = vec3(-1658.05, -3153.27, 13.90)
    },
    VIPS = {
        CITY = false,
        JDM = false,
        CITY2 = false,
        VILLAGE = false,
        MOTORCYCLES = false,
        SANDY = false,
        BOATS = false,
       -- BV = true,
        VIP = true,
        --DRIFT = true
        --AIRPLANE = false,
        --AIRVIP = true,
        --HELICOPTERS = false,
        --HELIVIP = true
    },
    BLIPS = {
        CITY = {
            coords = vec3(-31.79, -1113.89, 26.42),
            sprite = 227,
            colour = 4,
            text = 'Concesionario Low-Cost'
        },
        JDM = {
            coords = vec3(1133.79, -3139.89, 26.42),
            sprite = 227,
            colour = 4,
            text = 'Concesionario Muscle y JDM'
        },
        CITY2 = {
            coords = vec3(-612.12, -2236.36, 5.17),
            sprite = 227,
            colour = 4,
            text = 'Concesionario'
        },
        MOTORCYCLES = {
            coords = vec3(294.91, -1168.11, 29.67),
            sprite = 522,
            colour = 4,
            text = 'Motocicletas'
        },
        VILLAGE = {
            coords = vec3(63.56, 6476.29, 41.26),
            sprite = 227,
            colour = 4,
            text = 'Concesionario SUV Paleto'
        },
        SANDY = {
            coords = vec3(1230.17, 2731.05, 38.01),
            sprite = 227,
            colour = 4,
            text = 'Concesionario Compra-venta'
        },
        BOATS = {
            coords = vec3(-698.7, -1283.9, 9.55),
            sprite = 410,
            colour = 4,
            text = 'Concesionario Maritimo'
        },
        -- BV = {
        --     coords = vec3(-698.7, -1283.9, 9.55),
        --      sprite = 410,
        --      colour = 4,
        --      text = 'Concesionario Maritimo'
        --  },
        VIP = {
            coords = vec3(432.4, 235.31, 9.55),
            sprite = 227,
            colour = 4,
            text = 'Concesionario VIP'
        },
        -- DRIFT = {
        --     coords = vec3(953.22, -1698.37, 128.3),
        --     sprite = 227,
        --     colour = 4,
        --     text = 'Concesionario DRIFT'
        -- },
        -- AIRPLANE = {
        --     coords = vec3(-1270.19, -3378.04, 14.80),
        --     sprite = 423,
        --     colour = 4,
        --     text = 'Aviones'
        -- },
        -- AIRVIP = {
        --     coords = vec3(-970.92, -2999.66, 14.80),
        --     sprite = 423,
        --     colour = 4,
        --     text = 'Aviones VIP'
        -- },
        -- HELICOPTERS = {
        --     coords = vec3(-1064.51, -2904.07, 13.90),
        --     sprite = 43,
        --     colour = 4,
        --     text = 'Helicópteros'
        -- },
        -- HELIVIP = {
        --     coords = vec3(-1658.05, -3153.27, 13.90),
        --     sprite = 43,
        --     colour = 4,
        --     text = 'Helicópteros VIP'
        -- },
    },
    COLOURS = {
        { primary = 0, secondary = 0 }, -- black
        { primary = 111, secondary = 0 }, -- white
        { primary = 13, secondary = 0 }, -- gray
        { primary = 27, secondary = 0 }, -- red
        { primary = 64, secondary = 0 } -- blue
    },
}